LANGUAGES = {
    'ru': 'Русский',
    'en': 'English',
    'de': 'Deutsch',
    'es': 'Español',
    'pt': 'Português',
    'tr': 'Türkçe',
}

ROLE_PERFORMER = 'performer'
ROLE_CLIENT = 'client'

TEXTS = {
    'ru': {
        'welcome': 'Добро пожаловать в <b>{brand}</b>! Выберите язык.',
        'choose_role': 'Теперь выберите вашу роль.',
        'main_menu': 'Главное меню <b>{brand}</b>\n\nЯзык: <b>{language}</b>\nРоль: <b>{role}</b>',
        'performer': 'Исполнитель',
        'client': 'Заказчик',
        'menu_profile': 'Профиль',
        'menu_tasks': 'Задания',
        'menu_wallet': 'Кошелёк',
        'menu_history': 'История',
        'menu_campaigns': 'Кампании',
        'menu_stats': 'Аналитика',
        'menu_change_role': 'Сменить роль',
        'menu_change_language': 'Сменить язык',
        'back_to_language': 'Назад к языкам',
        'back_to_menu': 'В меню',
        'back_to_tasks': 'К заданиям',
        'refresh_screen': 'Обновить',
        'required_subscription_text': 'Чтобы продолжить, подпишитесь на обязательный чат и затем нажмите кнопку проверки.',
        'open_required_chat': 'Открыть чат',
        'check_subscription': 'Проверить подписку',
        'subscription_missing': 'Сначала вступите в обязательный чат, затем повторите проверку.',
        'subscription_success': 'Подписка подтверждена.',
        'subscription_not_required_here': 'Внутри обязательного чата дополнительная проверка не нужна.',
        'language_updated': 'Язык обновлён.',
        'role_updated': 'Роль обновлена.',
        'stale_screen': 'Этот экран уже неактуален. Используйте последнее сообщение бота.',
        'screen_refreshed': 'Экран обновлён.',
        'section_stub': '<b>{title}</b>\n\nРаздел подключён к общей навигации {brand}. Следующий этап наполнит его рабочей логикой.\n\nТекущая роль: <b>{role}</b>.',
        'profile_screen': '<b>Профиль исполнителя</b>\n\nID: <code>{user_id}</code>\nРоль: <b>{role}</b>\nАктивных заданий: <b>{active_tasks}/{task_limit}</b>\nБаланс доступный: <b>{available}</b> XTR\nВ холде: <b>{hold}</b> XTR\nВсего заработано: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Доступные задания</b>\n\nАктивных сейчас: <b>{active_tasks}/{task_limit}</b>\nНиже показаны задания, которые ещё можно взять.',
        'tasks_empty': '<b>Доступные задания</b>\n\nСейчас новых заданий нет. Обновите экран позже.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nТип: <b>{task_type}</b>\nНаграда: <b>{reward}</b> XTR\nДоступно: <b>{remaining}</b>\n\nСтатус: <b>{status}</b>\n\nОткройте цель задания, затем возьмите его или отправьте подтверждение.',
        'task_detail_taken': 'взято',
        'task_detail_available': 'доступно',
        'task_detail_submitted': 'подтверждение уже отправлено',
        'open_task_target': 'Открыть цель задания',
        'take_task_button': 'Взять задание',
        'submit_task_button': 'Отправить на проверку',
        'open_task_submission': 'Вернуться к заданию',
        'cancel_proof_input': 'Отменить ввод',
        'task_taken': 'Задание взято. После выполнения отправьте подтверждение.',
        'task_not_found': 'Задание не найдено.',
        'task_not_available': 'Это задание сейчас недоступно.',
        'task_repeat_blocked': 'Повторное выполнение этого задания запрещено.',
        'task_limit_reached': 'Достигнут лимит активных заданий. Завершите текущие или ускорьте холд через VIP позже.',
        'proof_prompt': '<b>Подтверждение выполнения</b>\n\nОтправьте одним сообщением ссылку, @username, ID поста или краткое описание того, что вы сделали. После получения бот сразу начислит награду в холд.',
        'proof_empty': 'Подтверждение пустое. Отправьте текст одним сообщением.',
        'proof_accepted': 'Подтверждение принято. Награда начислена в холд.',
        'proof_already_sent': 'Подтверждение по этому заданию уже было отправлено.',
        'proof_input_cancelled': 'Ввод подтверждения отменён.',
        'wallet_screen': '<b>Кошелёк</b>\n\nДоступно: <b>{available}</b> XTR\nВ холде: <b>{hold}</b> XTR\nВнутренний баланс: <b>{internal}</b>\nВсего заработано: <b>{earned}</b> XTR\nВыведено: <b>{withdrawn}</b> XTR\nОсвобождено холдов сейчас: <b>{released}</b>',
        'history_screen': '<b>История операций</b>\n\n{items}',
        'history_empty': 'Операций пока нет.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Освобождено холдов: <b>{released}</b>.',
    },
    'en': {
        'welcome': 'Welcome to <b>{brand}</b>! Choose your language.',
        'choose_role': 'Now choose your role.',
        'main_menu': 'Main menu <b>{brand}</b>\n\nLanguage: <b>{language}</b>\nRole: <b>{role}</b>',
        'performer': 'Performer',
        'client': 'Client',
        'menu_profile': 'Profile',
        'menu_tasks': 'Tasks',
        'menu_wallet': 'Wallet',
        'menu_history': 'History',
        'menu_campaigns': 'Campaigns',
        'menu_stats': 'Analytics',
        'menu_change_role': 'Change role',
        'menu_change_language': 'Change language',
        'back_to_language': 'Back to languages',
        'back_to_menu': 'To menu',
        'back_to_tasks': 'Back to tasks',
        'refresh_screen': 'Refresh',
        'required_subscription_text': 'To continue, join the required chat and then press the verification button.',
        'open_required_chat': 'Open chat',
        'check_subscription': 'Check subscription',
        'subscription_missing': 'Join the required chat first, then try the verification again.',
        'subscription_success': 'Subscription confirmed.',
        'subscription_not_required_here': 'Inside the required chat this check is not needed.',
        'language_updated': 'Language updated.',
        'role_updated': 'Role updated.',
        'stale_screen': 'This screen is outdated. Use the latest bot message.',
        'screen_refreshed': 'Screen refreshed.',
        'section_stub': '<b>{title}</b>\n\nThis section is already wired into the shared {brand} navigation. A later stage will fill it with working logic.\n\nCurrent role: <b>{role}</b>.',
        'profile_screen': '<b>Performer profile</b>\n\nID: <code>{user_id}</code>\nRole: <b>{role}</b>\nActive tasks: <b>{active_tasks}/{task_limit}</b>\nAvailable balance: <b>{available}</b> XTR\nIn hold: <b>{hold}</b> XTR\nLifetime earned: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Available tasks</b>\n\nActive now: <b>{active_tasks}/{task_limit}</b>\nTasks below can still be taken.',
        'tasks_empty': '<b>Available tasks</b>\n\nThere are no new tasks right now. Refresh later.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nType: <b>{task_type}</b>\nReward: <b>{reward}</b> XTR\nRemaining: <b>{remaining}</b>\n\nStatus: <b>{status}</b>\n\nOpen the target, then take the task or submit proof.',
        'task_detail_taken': 'taken',
        'task_detail_available': 'available',
        'task_detail_submitted': 'proof already sent',
        'open_task_target': 'Open task target',
        'take_task_button': 'Take task',
        'submit_task_button': 'Send for review',
        'open_task_submission': 'Back to task',
        'cancel_proof_input': 'Cancel input',
        'task_taken': 'Task taken. Send proof after completion.',
        'task_not_found': 'Task not found.',
        'task_not_available': 'This task is currently unavailable.',
        'task_repeat_blocked': 'Repeating this task is not allowed.',
        'task_limit_reached': 'You reached the active task limit. Finish current tasks first.',
        'proof_prompt': '<b>Task proof</b>\n\nSend one message with a link, @username, post ID or a short description of what you did. The reward will be placed into hold right away.',
        'proof_empty': 'Proof is empty. Send it as one text message.',
        'proof_accepted': 'Proof accepted. Reward placed into hold.',
        'proof_already_sent': 'Proof for this task has already been sent.',
        'proof_input_cancelled': 'Proof input cancelled.',
        'wallet_screen': '<b>Wallet</b>\n\nAvailable: <b>{available}</b> XTR\nIn hold: <b>{hold}</b> XTR\nInternal balance: <b>{internal}</b>\nLifetime earned: <b>{earned}</b> XTR\nWithdrawn: <b>{withdrawn}</b> XTR\nReleased now: <b>{released}</b>',
        'history_screen': '<b>Transaction history</b>\n\n{items}',
        'history_empty': 'No operations yet.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Released holds: <b>{released}</b>.',
    },
    'de': {
        'welcome': 'Willkommen bei <b>{brand}</b>! Wähle deine Sprache.',
        'choose_role': 'Wähle jetzt deine Rolle.',
        'main_menu': 'Hauptmenü <b>{brand}</b>\n\nSprache: <b>{language}</b>\nRolle: <b>{role}</b>',
        'performer': 'Ausführender',
        'client': 'Kunde',
        'menu_profile': 'Profil',
        'menu_tasks': 'Aufgaben',
        'menu_wallet': 'Wallet',
        'menu_history': 'Verlauf',
        'menu_campaigns': 'Kampagnen',
        'menu_stats': 'Analytik',
        'menu_change_role': 'Rolle ändern',
        'menu_change_language': 'Sprache ändern',
        'back_to_language': 'Zurück zu Sprachen',
        'back_to_menu': 'Zum Menü',
        'back_to_tasks': 'Zu Aufgaben',
        'refresh_screen': 'Aktualisieren',
        'required_subscription_text': 'Um fortzufahren, tritt dem Pflicht-Chat bei und drücke dann auf die Prüftaste.',
        'open_required_chat': 'Chat öffnen',
        'check_subscription': 'Abo prüfen',
        'subscription_missing': 'Bitte tritt zuerst dem Pflicht-Chat bei und versuche die Prüfung erneut.',
        'subscription_success': 'Abo bestätigt.',
        'subscription_not_required_here': 'Innerhalb des Pflicht-Chats ist diese Prüfung nicht nötig.',
        'language_updated': 'Sprache aktualisiert.',
        'role_updated': 'Rolle aktualisiert.',
        'stale_screen': 'Dieser Bildschirm ist veraltet. Nutze die letzte Bot-Nachricht.',
        'screen_refreshed': 'Bildschirm aktualisiert.',
        'section_stub': '<b>{title}</b>\n\nDieser Bereich ist bereits an die gemeinsame Navigation von {brand} angeschlossen. In einer späteren Phase kommt die Arbeitslogik hinzu.\n\nAktuelle Rolle: <b>{role}</b>.',
        'profile_screen': '<b>Ausführenden-Profil</b>\n\nID: <code>{user_id}</code>\nRolle: <b>{role}</b>\nAktive Aufgaben: <b>{active_tasks}/{task_limit}</b>\nVerfügbar: <b>{available}</b> XTR\nIm Hold: <b>{hold}</b> XTR\nGesamt verdient: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Verfügbare Aufgaben</b>\n\nAktiv jetzt: <b>{active_tasks}/{task_limit}</b>\nDie folgenden Aufgaben können noch übernommen werden.',
        'tasks_empty': '<b>Verfügbare Aufgaben</b>\n\nIm Moment gibt es keine neuen Aufgaben.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nTyp: <b>{task_type}</b>\nBelohnung: <b>{reward}</b> XTR\nVerbleibend: <b>{remaining}</b>\n\nStatus: <b>{status}</b>\n\nÖffne das Ziel und übernimm die Aufgabe oder sende den Nachweis.',
        'task_detail_taken': 'übernommen',
        'task_detail_available': 'verfügbar',
        'task_detail_submitted': 'Nachweis bereits gesendet',
        'open_task_target': 'Ziel öffnen',
        'take_task_button': 'Aufgabe übernehmen',
        'submit_task_button': 'Zur Prüfung senden',
        'open_task_submission': 'Zurück zur Aufgabe',
        'cancel_proof_input': 'Eingabe abbrechen',
        'task_taken': 'Aufgabe übernommen. Sende danach den Nachweis.',
        'task_not_found': 'Aufgabe nicht gefunden.',
        'task_not_available': 'Diese Aufgabe ist derzeit nicht verfügbar.',
        'task_repeat_blocked': 'Diese Aufgabe darf nicht wiederholt werden.',
        'task_limit_reached': 'Limit aktiver Aufgaben erreicht.',
        'proof_prompt': '<b>Nachweis</b>\n\nSende eine Nachricht mit Link, @username, Post-ID oder kurzer Beschreibung. Die Belohnung geht sofort in den Hold.',
        'proof_empty': 'Der Nachweis ist leer.',
        'proof_accepted': 'Nachweis akzeptiert. Belohnung im Hold.',
        'proof_already_sent': 'Der Nachweis wurde bereits gesendet.',
        'proof_input_cancelled': 'Eingabe abgebrochen.',
        'wallet_screen': '<b>Wallet</b>\n\nVerfügbar: <b>{available}</b> XTR\nIm Hold: <b>{hold}</b> XTR\nInternes Guthaben: <b>{internal}</b>\nGesamt verdient: <b>{earned}</b> XTR\nAusgezahlt: <b>{withdrawn}</b> XTR\nJetzt freigegeben: <b>{released}</b>',
        'history_screen': '<b>Transaktionsverlauf</b>\n\n{items}',
        'history_empty': 'Noch keine Vorgänge.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Freigegebene Holds: <b>{released}</b>.',
    },
    'es': {
        'welcome': 'Bienvenido a <b>{brand}</b>. Elige tu idioma.',
        'choose_role': 'Ahora elige tu rol.',
        'main_menu': 'Menú principal <b>{brand}</b>\n\nIdioma: <b>{language}</b>\nRol: <b>{role}</b>',
        'performer': 'Ejecutor',
        'client': 'Cliente',
        'menu_profile': 'Perfil',
        'menu_tasks': 'Tareas',
        'menu_wallet': 'Billetera',
        'menu_history': 'Historial',
        'menu_campaigns': 'Campañas',
        'menu_stats': 'Analítica',
        'menu_change_role': 'Cambiar rol',
        'menu_change_language': 'Cambiar idioma',
        'back_to_language': 'Volver a idiomas',
        'back_to_menu': 'Al menú',
        'back_to_tasks': 'A tareas',
        'refresh_screen': 'Actualizar',
        'required_subscription_text': 'Para continuar, únete al chat obligatorio y luego pulsa el botón de verificación.',
        'open_required_chat': 'Abrir chat',
        'check_subscription': 'Verificar suscripción',
        'subscription_missing': 'Primero únete al chat obligatorio y luego repite la verificación.',
        'subscription_success': 'Suscripción confirmada.',
        'subscription_not_required_here': 'Dentro del chat obligatorio no hace falta esta comprobación.',
        'language_updated': 'Idioma actualizado.',
        'role_updated': 'Rol actualizado.',
        'stale_screen': 'Esta pantalla ya no es válida. Usa el último mensaje del bot.',
        'screen_refreshed': 'Pantalla actualizada.',
        'section_stub': '<b>{title}</b>\n\nEsta sección ya está conectada a la navegación compartida de {brand}. En una etapa posterior recibirá la lógica funcional.\n\nRol actual: <b>{role}</b>.',
        'profile_screen': '<b>Perfil del ejecutor</b>\n\nID: <code>{user_id}</code>\nRol: <b>{role}</b>\nTareas activas: <b>{active_tasks}/{task_limit}</b>\nDisponible: <b>{available}</b> XTR\nEn retención: <b>{hold}</b> XTR\nGanado total: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Tareas disponibles</b>\n\nActivas ahora: <b>{active_tasks}/{task_limit}</b>\nLas tareas siguientes aún se pueden tomar.',
        'tasks_empty': '<b>Tareas disponibles</b>\n\nAhora no hay tareas nuevas.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nTipo: <b>{task_type}</b>\nRecompensa: <b>{reward}</b> XTR\nRestantes: <b>{remaining}</b>\n\nEstado: <b>{status}</b>\n\nAbre el objetivo y luego toma la tarea o envía la prueba.',
        'task_detail_taken': 'tomada',
        'task_detail_available': 'disponible',
        'task_detail_submitted': 'prueba ya enviada',
        'open_task_target': 'Abrir objetivo',
        'take_task_button': 'Tomar tarea',
        'submit_task_button': 'Enviar a revisión',
        'open_task_submission': 'Volver a la tarea',
        'cancel_proof_input': 'Cancelar entrada',
        'task_taken': 'Tarea tomada. Envía la prueba después.',
        'task_not_found': 'Tarea no encontrada.',
        'task_not_available': 'Esta tarea no está disponible ahora.',
        'task_repeat_blocked': 'No se permite repetir esta tarea.',
        'task_limit_reached': 'Se alcanzó el límite de tareas activas.',
        'proof_prompt': '<b>Prueba de tarea</b>\n\nEnvía un mensaje con enlace, @usuario, ID de publicación o una breve descripción. La recompensa irá a retención de inmediato.',
        'proof_empty': 'La prueba está vacía.',
        'proof_accepted': 'Prueba aceptada. Recompensa en retención.',
        'proof_already_sent': 'La prueba ya fue enviada.',
        'proof_input_cancelled': 'Entrada cancelada.',
        'wallet_screen': '<b>Billetera</b>\n\nDisponible: <b>{available}</b> XTR\nEn retención: <b>{hold}</b> XTR\nSaldo interno: <b>{internal}</b>\nGanado total: <b>{earned}</b> XTR\nRetirado: <b>{withdrawn}</b> XTR\nLiberado ahora: <b>{released}</b>',
        'history_screen': '<b>Historial de operaciones</b>\n\n{items}',
        'history_empty': 'Aún no hay operaciones.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Retenciones liberadas: <b>{released}</b>.',
    },
    'pt': {
        'welcome': 'Bem-vindo ao <b>{brand}</b>! Escolha seu idioma.',
        'choose_role': 'Agora escolha seu papel.',
        'main_menu': 'Menu principal <b>{brand}</b>\n\nIdioma: <b>{language}</b>\nPapel: <b>{role}</b>',
        'performer': 'Executor',
        'client': 'Cliente',
        'menu_profile': 'Perfil',
        'menu_tasks': 'Tarefas',
        'menu_wallet': 'Carteira',
        'menu_history': 'Histórico',
        'menu_campaigns': 'Campanhas',
        'menu_stats': 'Análises',
        'menu_change_role': 'Trocar papel',
        'menu_change_language': 'Trocar idioma',
        'back_to_language': 'Voltar aos idiomas',
        'back_to_menu': 'Ao menu',
        'back_to_tasks': 'Para tarefas',
        'refresh_screen': 'Atualizar',
        'required_subscription_text': 'Para continuar, entre no chat obrigatório e depois pressione o botão de verificação.',
        'open_required_chat': 'Abrir chat',
        'check_subscription': 'Verificar inscrição',
        'subscription_missing': 'Entre primeiro no chat obrigatório e depois tente a verificação novamente.',
        'subscription_success': 'Inscrição confirmada.',
        'subscription_not_required_here': 'Dentro do chat obrigatório essa verificação não é necessária.',
        'language_updated': 'Idioma atualizado.',
        'role_updated': 'Papel atualizado.',
        'stale_screen': 'Esta tela já está desatualizada. Use a mensagem mais recente do bot.',
        'screen_refreshed': 'Tela atualizada.',
        'section_stub': '<b>{title}</b>\n\nEsta seção já está ligada à navegação compartilhada do {brand}. Uma etapa posterior adicionará a lógica funcional.\n\nPapel atual: <b>{role}</b>.',
        'profile_screen': '<b>Perfil do executor</b>\n\nID: <code>{user_id}</code>\nPapel: <b>{role}</b>\nTarefas ativas: <b>{active_tasks}/{task_limit}</b>\nDisponível: <b>{available}</b> XTR\nEm hold: <b>{hold}</b> XTR\nTotal ganho: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Tarefas disponíveis</b>\n\nAtivas agora: <b>{active_tasks}/{task_limit}</b>\nAs tarefas abaixo ainda podem ser aceitas.',
        'tasks_empty': '<b>Tarefas disponíveis</b>\n\nNão há novas tarefas agora.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nTipo: <b>{task_type}</b>\nRecompensa: <b>{reward}</b> XTR\nRestantes: <b>{remaining}</b>\n\nStatus: <b>{status}</b>\n\nAbra o alvo e depois aceite a tarefa ou envie a prova.',
        'task_detail_taken': 'aceita',
        'task_detail_available': 'disponível',
        'task_detail_submitted': 'prova já enviada',
        'open_task_target': 'Abrir alvo',
        'take_task_button': 'Aceitar tarefa',
        'submit_task_button': 'Enviar para revisão',
        'open_task_submission': 'Voltar à tarefa',
        'cancel_proof_input': 'Cancelar entrada',
        'task_taken': 'Tarefa aceita. Envie a prova depois.',
        'task_not_found': 'Tarefa não encontrada.',
        'task_not_available': 'Esta tarefa não está disponível agora.',
        'task_repeat_blocked': 'Não é permitido repetir esta tarefa.',
        'task_limit_reached': 'O limite de tarefas ativas foi atingido.',
        'proof_prompt': '<b>Prova da tarefa</b>\n\nEnvie uma mensagem com link, @usuário, ID do post ou uma breve descrição. A recompensa vai para hold imediatamente.',
        'proof_empty': 'A prova está vazia.',
        'proof_accepted': 'Prova aceita. Recompensa em hold.',
        'proof_already_sent': 'A prova já foi enviada.',
        'proof_input_cancelled': 'Entrada cancelada.',
        'wallet_screen': '<b>Carteira</b>\n\nDisponível: <b>{available}</b> XTR\nEm hold: <b>{hold}</b> XTR\nSaldo interno: <b>{internal}</b>\nTotal ganho: <b>{earned}</b> XTR\nRetirado: <b>{withdrawn}</b> XTR\nLiberado agora: <b>{released}</b>',
        'history_screen': '<b>Histórico de operações</b>\n\n{items}',
        'history_empty': 'Ainda não há operações.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Holds liberados: <b>{released}</b>.',
    },
    'tr': {
        'welcome': '<b>{brand}</b>\'a hoş geldin! Dilini seç.',
        'choose_role': 'Şimdi rolünü seç.',
        'main_menu': 'Ana menü <b>{brand}</b>\n\nDil: <b>{language}</b>\nRol: <b>{role}</b>',
        'performer': 'Görev yapan',
        'client': 'Müşteri',
        'menu_profile': 'Profil',
        'menu_tasks': 'Görevler',
        'menu_wallet': 'Cüzdan',
        'menu_history': 'Geçmiş',
        'menu_campaigns': 'Kampanyalar',
        'menu_stats': 'Analitik',
        'menu_change_role': 'Rol değiştir',
        'menu_change_language': 'Dil değiştir',
        'back_to_language': 'Dillere dön',
        'back_to_menu': 'Menüye dön',
        'back_to_tasks': 'Görevlere dön',
        'refresh_screen': 'Yenile',
        'required_subscription_text': 'Devam etmek için zorunlu sohbete katıl ve sonra doğrulama düğmesine bas.',
        'open_required_chat': 'Sohbeti aç',
        'check_subscription': 'Aboneliği kontrol et',
        'subscription_missing': 'Önce zorunlu sohbete katıl, sonra doğrulamayı tekrar dene.',
        'subscription_success': 'Abonelik doğrulandı.',
        'subscription_not_required_here': 'Zorunlu sohbetin içinde bu kontrol gerekli değil.',
        'language_updated': 'Dil güncellendi.',
        'role_updated': 'Rol güncellendi.',
        'stale_screen': 'Bu ekran artık geçersiz. Botun son mesajını kullan.',
        'screen_refreshed': 'Ekran yenilendi.',
        'section_stub': '<b>{title}</b>\n\nBu bölüm zaten {brand} ortak gezintisine bağlandı. Sonraki bir aşama çalışan mantığı ekleyecek.\n\nGeçerli rol: <b>{role}</b>.',
        'profile_screen': '<b>Görev yapan profili</b>\n\nID: <code>{user_id}</code>\nRol: <b>{role}</b>\nAktif görevler: <b>{active_tasks}/{task_limit}</b>\nKullanılabilir bakiye: <b>{available}</b> XTR\nHold bakiyesi: <b>{hold}</b> XTR\nToplam kazanç: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Uygun görevler</b>\n\nŞu an aktif: <b>{active_tasks}/{task_limit}</b>\nAşağıdaki görevler hâlâ alınabilir.',
        'tasks_empty': '<b>Uygun görevler</b>\n\nŞu anda yeni görev yok.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nTür: <b>{task_type}</b>\nÖdül: <b>{reward}</b> XTR\nKalan: <b>{remaining}</b>\n\nDurum: <b>{status}</b>\n\nHedefi aç, sonra görevi al veya kanıtı gönder.',
        'task_detail_taken': 'alındı',
        'task_detail_available': 'uygun',
        'task_detail_submitted': 'kanıt zaten gönderildi',
        'open_task_target': 'Görev hedefini aç',
        'take_task_button': 'Görevi al',
        'submit_task_button': 'İncelemeye gönder',
        'open_task_submission': 'Göreve dön',
        'cancel_proof_input': 'Girişi iptal et',
        'task_taken': 'Görev alındı. Tamamlayınca kanıt gönder.',
        'task_not_found': 'Görev bulunamadı.',
        'task_not_available': 'Bu görev şu anda uygun değil.',
        'task_repeat_blocked': 'Bu görevi tekrar yapmak yasak.',
        'task_limit_reached': 'Aktif görev limiti doldu.',
        'proof_prompt': '<b>Görev kanıtı</b>\n\nBağlantı, @kullanıcı, gönderi kimliği veya kısa açıklama içeren tek mesaj gönder. Ödül hemen hold bakiyesine eklenir.',
        'proof_empty': 'Kanıt boş.',
        'proof_accepted': 'Kanıt kabul edildi. Ödül hold bakiyesine eklendi.',
        'proof_already_sent': 'Bu görev için kanıt zaten gönderildi.',
        'proof_input_cancelled': 'Girdi iptal edildi.',
        'wallet_screen': '<b>Cüzdan</b>\n\nKullanılabilir: <b>{available}</b> XTR\nHold: <b>{hold}</b> XTR\nİç bakiye: <b>{internal}</b>\nToplam kazanç: <b>{earned}</b> XTR\nÇekilen: <b>{withdrawn}</b> XTR\nŞimdi açılan: <b>{released}</b>',
        'history_screen': '<b>İşlem geçmişi</b>\n\n{items}',
        'history_empty': 'Henüz işlem yok.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Açılan holdlar: <b>{released}</b>.',
    },
}


_STAGE5_TEXTS_EN = {
    'campaign_client_only': 'This section is available only for the client role.',
    'campaigns_screen': '<b>Your campaigns</b>\n\nTotal: <b>{total}</b>\nActive: <b>{active}</b>\nPaused: <b>{paused}</b>\nDrafts: <b>{drafts}</b>\n\nOpen a card below or create a new campaign.',
    'campaigns_empty': '<b>Your campaigns</b>\n\nThere are no campaigns yet. Create the first one below.',
    'campaign_create_button': 'Create campaign',
    'back_to_campaigns': 'Back to campaigns',
    'campaign_row': 'Campaign #{campaign_id} · {title} · {status}',
    'campaign_create_intro': '<b>Create campaign</b>\n\nChoose a task type for the new campaign.',
    'campaign_type_saved': 'Task type selected.',
    'campaign_task_type_channel_subscribe': 'Subscribe to channel',
    'campaign_task_type_chat_join': 'Join chat',
    'campaign_task_type_post_view': 'View post',
    'campaign_task_type_bot_start': 'Start bot',
    'campaign_task_type_mini_app_open': 'Open Mini App',
    'campaign_input_screen': '<b>Campaign setup</b>\n\nType: <b>{task_type}</b>\nTarget: <code>{target_url}</code>\nReward: <b>{reward}</b> XTR\nQuantity: <b>{quantity}</b>\n\n{step}',
    'campaign_target_prompt': 'Send the target link or @username in one message.',
    'campaign_reward_prompt': 'Send the reward per completion as a whole number in XTR.',
    'campaign_quantity_prompt': 'Send the number of required completions as a whole number.',
    'campaign_target_saved': 'Target saved.',
    'campaign_reward_saved': 'Reward saved.',
    'campaign_quantity_saved': 'Quantity saved. Check the preview below.',
    'campaign_target_invalid': 'Target is invalid. Send a valid Telegram or web link.',
    'campaign_reward_invalid': 'Reward must be a positive whole number from 1 to 100000.',
    'campaign_quantity_invalid': 'Quantity must be a positive whole number from 1 to 100000.',
    'campaign_invalid_task_type': 'Unsupported task type.',
    'campaign_draft_missing': 'Campaign draft was not found. Start creation again.',
    'campaign_preview_screen': '<b>Campaign preview</b>\n\nType: <b>{task_type}</b>\nTarget: <code>{target_url}</code>\nReward: <b>{reward}</b> XTR\nQuantity: <b>{quantity}</b>\nBudget: <b>{budget}</b> XTR\n\nSave as draft or launch immediately.',
    'campaign_save_draft_button': 'Save draft',
    'campaign_launch_now_button': 'Launch now',
    'campaign_cancel_button': 'Cancel',
    'campaign_create_cancelled': 'Campaign creation cancelled.',
    'campaign_created_draft': 'Campaign saved as draft.',
    'campaign_created_active': 'Campaign created and launched.',
    'campaign_card_screen': '<b>Campaign #{campaign_id}</b>\n\nTitle: <b>{title}</b>\nType: <b>{task_type}</b>\nTarget: <code>{target_url}</code>\nReward: <b>{reward}</b> XTR\nQuantity: <b>{quantity}</b>\nCompleted: <b>{completed}</b>\nRejected: <b>{rejected}</b>\nBudget: <b>{budget_total}</b> XTR\nSpent: <b>{budget_spent}</b> XTR\nReserved: <b>{budget_reserved}</b> XTR\nRemaining: <b>{budget_remaining}</b> XTR\nStatus: <b>{status}</b>',
    'campaign_not_found': 'Campaign not found.',
    'campaign_status_draft': 'draft',
    'campaign_status_active': 'active',
    'campaign_status_paused': 'paused',
    'campaign_status_completed': 'completed',
    'campaign_status_archived': 'archived',
    'campaign_launch_button': 'Launch campaign',
    'campaign_pause_button': 'Pause campaign',
    'campaign_resume_button': 'Resume campaign',
    'campaign_launched': 'Campaign launched.',
    'campaign_paused': 'Campaign paused.',
    'campaign_resumed': 'Campaign resumed.',
    'campaign_status_invalid': 'Unsupported campaign status.',
    'campaign_status_transition_invalid': 'This status change is not allowed right now.',
    'campaign_stats_screen': '<b>Campaign analytics</b>\n\nTotal campaigns: <b>{total}</b>\nActive: <b>{active}</b>\nPaused: <b>{paused}</b>\nDrafts: <b>{drafts}</b>\nCompleted actions: <b>{completed}</b>\nRejected actions: <b>{rejected}</b>\nTotal budget: <b>{budget}</b> XTR\nSpent: <b>{spent}</b> XTR\nReserved: <b>{reserved}</b> XTR\nRemaining: <b>{remaining}</b> XTR',
}

_STAGE5_TEXTS_RU = {
    'campaign_client_only': 'Этот раздел доступен только для роли заказчика.',
    'campaigns_screen': '<b>Ваши кампании</b>\n\nВсего: <b>{total}</b>\nАктивных: <b>{active}</b>\nНа паузе: <b>{paused}</b>\nЧерновиков: <b>{drafts}</b>\n\nОткройте карточку ниже или создайте новую кампанию.',
    'campaigns_empty': '<b>Ваши кампании</b>\n\nПока нет ни одной кампании. Ниже можно создать первую.',
    'campaign_create_button': 'Создать кампанию',
    'back_to_campaigns': 'К кампаниям',
    'campaign_row': 'Кампания #{campaign_id} · {title} · {status}',
    'campaign_create_intro': '<b>Создание кампании</b>\n\nВыберите тип задания для новой кампании.',
    'campaign_type_saved': 'Тип задания выбран.',
    'campaign_task_type_channel_subscribe': 'Подписка на канал',
    'campaign_task_type_chat_join': 'Вступление в чат',
    'campaign_task_type_post_view': 'Просмотр поста',
    'campaign_task_type_bot_start': 'Запуск бота',
    'campaign_task_type_mini_app_open': 'Открытие Mini App',
    'campaign_input_screen': '<b>Настройка кампании</b>\n\nТип: <b>{task_type}</b>\nЦель: <code>{target_url}</code>\nНаграда: <b>{reward}</b> XTR\nКоличество: <b>{quantity}</b>\n\n{step}',
    'campaign_target_prompt': 'Отправьте ссылку на цель или @username одним сообщением.',
    'campaign_reward_prompt': 'Отправьте награду за одно выполнение целым числом в XTR.',
    'campaign_quantity_prompt': 'Отправьте нужное количество выполнений целым числом.',
    'campaign_target_saved': 'Цель сохранена.',
    'campaign_reward_saved': 'Награда сохранена.',
    'campaign_quantity_saved': 'Количество сохранено. Проверьте предпросмотр ниже.',
    'campaign_target_invalid': 'Цель указана неверно. Отправьте корректную ссылку Telegram или web.',
    'campaign_reward_invalid': 'Награда должна быть положительным целым числом от 1 до 100000.',
    'campaign_quantity_invalid': 'Количество должно быть положительным целым числом от 1 до 100000.',
    'campaign_invalid_task_type': 'Неподдерживаемый тип задания.',
    'campaign_draft_missing': 'Черновик кампании не найден. Начните создание заново.',
    'campaign_preview_screen': '<b>Предпросмотр кампании</b>\n\nТип: <b>{task_type}</b>\nЦель: <code>{target_url}</code>\nНаграда: <b>{reward}</b> XTR\nКоличество: <b>{quantity}</b>\nБюджет: <b>{budget}</b> XTR\n\nСохраните как черновик или запустите сразу.',
    'campaign_save_draft_button': 'Сохранить черновик',
    'campaign_launch_now_button': 'Запустить сразу',
    'campaign_cancel_button': 'Отменить',
    'campaign_create_cancelled': 'Создание кампании отменено.',
    'campaign_created_draft': 'Кампания сохранена как черновик.',
    'campaign_created_active': 'Кампания создана и запущена.',
    'campaign_card_screen': '<b>Кампания #{campaign_id}</b>\n\nНазвание: <b>{title}</b>\nТип: <b>{task_type}</b>\nЦель: <code>{target_url}</code>\nНаграда: <b>{reward}</b> XTR\nКоличество: <b>{quantity}</b>\nВыполнено: <b>{completed}</b>\nОтклонено: <b>{rejected}</b>\nБюджет: <b>{budget_total}</b> XTR\nПотрачено: <b>{budget_spent}</b> XTR\nВ резерве: <b>{budget_reserved}</b> XTR\nОстаток: <b>{budget_remaining}</b> XTR\nСтатус: <b>{status}</b>',
    'campaign_not_found': 'Кампания не найдена.',
    'campaign_status_draft': 'черновик',
    'campaign_status_active': 'активна',
    'campaign_status_paused': 'на паузе',
    'campaign_status_completed': 'завершена',
    'campaign_status_archived': 'в архиве',
    'campaign_launch_button': 'Запустить кампанию',
    'campaign_pause_button': 'Поставить на паузу',
    'campaign_resume_button': 'Возобновить кампанию',
    'campaign_launched': 'Кампания запущена.',
    'campaign_paused': 'Кампания поставлена на паузу.',
    'campaign_resumed': 'Кампания возобновлена.',
    'campaign_status_invalid': 'Неподдерживаемый статус кампании.',
    'campaign_status_transition_invalid': 'Сейчас такое изменение статуса недоступно.',
    'campaign_stats_screen': '<b>Аналитика кампаний</b>\n\nВсего кампаний: <b>{total}</b>\nАктивных: <b>{active}</b>\nНа паузе: <b>{paused}</b>\nЧерновиков: <b>{drafts}</b>\nВыполненных действий: <b>{completed}</b>\nОтклонённых действий: <b>{rejected}</b>\nОбщий бюджет: <b>{budget}</b> XTR\nПотрачено: <b>{spent}</b> XTR\nВ резерве: <b>{reserved}</b> XTR\nОстаток: <b>{remaining}</b> XTR',
}

TEXTS['en'].update(_STAGE5_TEXTS_EN)
TEXTS['ru'].update(_STAGE5_TEXTS_RU)
for _lang, _mapping in TEXTS.items():
    if _lang not in {'ru', 'en'}:
        for _key, _value in _STAGE5_TEXTS_EN.items():
            _mapping.setdefault(_key, _value)

_STAGE6_TEXTS_EN = {
    'menu_vip': 'VIP',
    'menu_rewards': 'Rewards',
    'menu_referrals': 'Referrals',
    'internal_currency_name': 'Boosts',
    'wallet_screen': '<b>Wallet</b>\n\nAvailable: <b>{available}</b> XTR\nIn hold: <b>{hold}</b> XTR\n{internal_name}: <b>{internal}</b>\nLifetime earned: <b>{earned}</b> XTR\nWithdrawn: <b>{withdrawn}</b> XTR\nReleased now: <b>{released}</b>',
    'history_row': '• {date} · {entry_type} · {amount} {currency} · {status}',
    'vip_screen': '<b>VIP center</b>\n\n{active_block}\n\nTotal bonuses now:\n• Hold speed: <b>{hold_speed}%</b>\n• Active task slots: <b>+{task_bonus}</b>\n• Queue priority: <b>{priority}</b>\n• Referral rate bonus: <b>+{ref_bonus}%</b>\n\nBuy a plan with {internal_name}.',
    'vip_no_active': 'No active VIP plans yet.',
    'vip_active_row': '• {title} — until <b>{expires_at}</b>',
    'vip_plan_7_title': 'VIP 7 days',
    'vip_plan_7_desc': '25% faster hold, +2 active tasks, queue priority 1, +2% referral rate.',
    'vip_plan_30_title': 'VIP 30 days',
    'vip_plan_30_desc': '50% faster hold, +5 active tasks, queue priority 2, +5% referral rate.',
    'vip_buy_button': 'Buy for {price} {internal_name}',
    'vip_plan_not_found': 'VIP plan not found.',
    'vip_balance_low': 'Not enough internal balance for this VIP plan.',
    'vip_purchase_success': 'VIP plan activated.',
    'rewards_screen': '<b>Rewards catalog</b>\n\nSpend {internal_name} on utility bonuses.\nCurrent balance: <b>{balance}</b> {internal_name}\n\nAvailable items:\n{items}',
    'reward_item_row': '• <b>{title}</b> — {price} {internal_name}\n{desc}',
    'reward_hold_boost_title': 'Speed booster · 3 days',
    'reward_hold_boost_desc': 'Extra 15% hold acceleration for 3 days.',
    'reward_slots_boost_title': 'Slot booster · 3 days',
    'reward_slots_boost_desc': 'Adds +1 active task slot for 3 days.',
    'reward_priority_boost_title': 'Priority booster · 3 days',
    'reward_priority_boost_desc': 'Priority queue level 1 and +1% referral rate for 3 days.',
    'reward_buy_button': 'Buy bonus',
    'reward_item_not_found': 'Reward item not found.',
    'reward_balance_low': 'Not enough internal balance for this bonus.',
    'reward_purchase_success': 'Bonus activated.',
    'rewards_claim_demo_button': 'Claim demo top up',
    'demo_topup_success': 'Demo top up credited to internal balance.',
    'demo_topup_disabled': 'Demo top up is disabled.',
    'demo_topup_already_claimed': 'Demo top up has already been claimed.',
    'referrals_screen': '<b>Referrals</b>\n\nYour link:\n<code>{link}</code>\n\nInvited: <b>{count}</b>\nEarned: <b>{earned}</b> {internal_name}\nCurrent referral rate: <b>{rate}%</b>\n\n{items}',
    'referrals_empty': 'No invited users yet. Share your link to start earning.',
    'referral_row': '• {name} — earned: <b>{earned}</b> {internal_name} · joined: <b>{joined}</b>',
}

_STAGE6_TEXTS_RU = {
    'menu_vip': 'VIP',
    'menu_rewards': 'Награды',
    'menu_referrals': 'Рефералы',
    'internal_currency_name': 'Бусты',
    'wallet_screen': '<b>Кошелёк</b>\n\nДоступно: <b>{available}</b> XTR\nВ холде: <b>{hold}</b> XTR\n{internal_name}: <b>{internal}</b>\nВсего заработано: <b>{earned}</b> XTR\nВыведено: <b>{withdrawn}</b> XTR\nОсвобождено холдов сейчас: <b>{released}</b>',
    'history_row': '• {date} · {entry_type} · {amount} {currency} · {status}',
    'vip_screen': '<b>VIP-центр</b>\n\n{active_block}\n\nСуммарные бонусы сейчас:\n• Ускорение холда: <b>{hold_speed}%</b>\n• Доп. лимит активных заданий: <b>+{task_bonus}</b>\n• Приоритет очереди: <b>{priority}</b>\n• Бонус к реферальной ставке: <b>+{ref_bonus}%</b>\n\nПокупайте планы за {internal_name}.',
    'vip_no_active': 'Активных VIP-планов пока нет.',
    'vip_active_row': '• {title} — действует до <b>{expires_at}</b>',
    'vip_plan_7_title': 'VIP на 7 дней',
    'vip_plan_7_desc': 'Холд быстрее на 25%, +2 активных задания, приоритет 1, +2% к реферальной ставке.',
    'vip_plan_30_title': 'VIP на 30 дней',
    'vip_plan_30_desc': 'Холд быстрее на 50%, +5 активных заданий, приоритет 2, +5% к реферальной ставке.',
    'vip_buy_button': 'Купить за {price} {internal_name}',
    'vip_plan_not_found': 'VIP-план не найден.',
    'vip_balance_low': 'Недостаточно внутренней валюты для покупки VIP.',
    'vip_purchase_success': 'VIP-план активирован.',
    'rewards_screen': '<b>Каталог наград</b>\n\nТратьте {internal_name} на полезные бонусы.\nТекущий баланс: <b>{balance}</b> {internal_name}\n\nДоступные бонусы:\n{items}',
    'reward_item_row': '• <b>{title}</b> — {price} {internal_name}\n{desc}',
    'reward_hold_boost_title': 'Ускоритель холда · 3 дня',
    'reward_hold_boost_desc': 'Дополнительное ускорение холда на 15% на 3 дня.',
    'reward_slots_boost_title': 'Слоты заданий · 3 дня',
    'reward_slots_boost_desc': 'Добавляет +1 активный слот заданий на 3 дня.',
    'reward_priority_boost_title': 'Приоритет · 3 дня',
    'reward_priority_boost_desc': 'Приоритет очереди 1 и +1% к реферальной ставке на 3 дня.',
    'reward_buy_button': 'Купить бонус',
    'reward_item_not_found': 'Такой бонус не найден.',
    'reward_balance_low': 'Недостаточно внутренней валюты для покупки бонуса.',
    'reward_purchase_success': 'Бонус активирован.',
    'rewards_claim_demo_button': 'Получить демо-пополнение',
    'demo_topup_success': 'Демо-пополнение зачислено на внутренний баланс.',
    'demo_topup_disabled': 'Демо-пополнение отключено.',
    'demo_topup_already_claimed': 'Демо-пополнение уже было получено.',
    'referrals_screen': '<b>Рефералы</b>\n\nВаша ссылка:\n<code>{link}</code>\n\nПриглашено: <b>{count}</b>\nЗаработано: <b>{earned}</b> {internal_name}\nТекущая реферальная ставка: <b>{rate}%</b>\n\n{items}',
    'referrals_empty': 'Пока нет приглашённых пользователей. Поделитесь ссылкой, чтобы начать зарабатывать.',
    'referral_row': '• {name} — заработано: <b>{earned}</b> {internal_name} · вступил: <b>{joined}</b>',
}

TEXTS['en'].update(_STAGE6_TEXTS_EN)
TEXTS['ru'].update(_STAGE6_TEXTS_RU)
for _lang, _mapping in TEXTS.items():
    if _lang not in {'ru', 'en'}:
        for _key, _value in _STAGE6_TEXTS_EN.items():
            _mapping.setdefault(_key, _value)

_STAGE7_TEXTS_EN = {
    'menu_admin': 'Admin',
    'blocked_screen': '<b>Access restricted</b>\n\nYour account is temporarily blocked. If you think this is a mistake, contact support: {support}',
    'blocked_alert': 'Your account is blocked.',
    'proof_prompt': '<b>Task proof</b>\n\nSend one message with a link, @username, post ID or a short description. Standard tasks are credited to hold automatically, suspicious ones go to manual review.',
    'proof_sent_manual_review': 'Proof received. The task was sent to manual review.',
    'task_detail_manual_review': 'on manual review',
    'task_detail_rejected': 'rejected',
    'admin_access_denied': 'Admin access denied.',
    'admin_home_screen': '<b>Admin panel</b>\n\nManual review queue: <b>{queue}</b>\nBlocked users: <b>{blocked}</b>\nHigh-risk users: <b>{high_risk}</b>\nRejected submissions: <b>{rejected}</b>',
    'admin_queue_button': 'Review queue',
    'admin_logs_button': 'Admin logs',
    'admin_queue_empty': '<b>Manual review queue</b>\n\nQueue is empty right now.',
    'admin_queue_screen': '<b>Manual review queue</b>\n\n{items}',
    'admin_queue_line': '• #{submission_id} · {title} · {performer} · sub risk {risk} / user risk {user_risk}',
    'admin_queue_row': '#{submission_id} · {title} · {performer} · R{risk}',
    'admin_submission_not_found': 'Submission not found.',
    'admin_submission_already_reviewed': 'This submission has already been reviewed.',
    'admin_submission_screen': '<b>Submission #{submission_id}</b>\n\nCampaign: <b>{title}</b>\nPerformer: <b>{performer}</b>\nPerformer ID: <code>{performer_id}</code>\nUser status: <b>{user_status}</b>\nSubmission status: <b>{submission_status}</b>\nReward: <b>{reward}</b> XTR\nSubmission risk: <b>{submission_risk}</b>\nUser risk: <b>{user_risk}</b>\nApproved / rejected / review: <b>{approved}</b> / <b>{rejected}</b> / <b>{review_count}</b>\nSubmitted at: <b>{submitted_at}</b>\nTarget: <code>{target}</code>\nReject reason: <b>{reject_reason}</b>\n\n<b>Proof</b>\n<blockquote>{proof}</blockquote>\n\n<b>Recent risk events</b>\n{events}',
    'admin_risk_event_row': '• {created} · {event_type} · +{score}',
    'admin_risk_events_empty': 'No recent risk events.',
    'admin_approve_button': 'Approve',
    'admin_reject_button': 'Reject',
    'admin_block_button': 'Block user',
    'admin_unblock_button': 'Unblock user',
    'admin_adjust_risk_button': 'Adjust risk',
    'admin_adjust_balance_button': 'Adjust balance',
    'admin_submission_approved': 'Submission approved. Reward placed into hold.',
    'admin_submission_rejected': 'Submission rejected.',
    'admin_reject_prompt': '<b>Reject submission #{submission_id}</b>\n\nSend one text message with the rejection reason. It will be stored in moderation history.',
    'admin_reject_reason_empty': 'Reject reason cannot be empty.',
    'admin_user_not_found': 'User not found.',
    'admin_cannot_block_admin': 'You cannot block another admin.',
    'admin_user_blocked': 'User blocked.',
    'admin_user_unblocked': 'User unblocked.',
    'admin_adjust_risk_prompt': '<b>Adjust risk score</b>\n\nTarget: <b>{target}</b> · <code>{user_id}</code>\nCurrent risk: <b>{current}</b>\n\nSend a signed integer, for example <code>+10</code> or <code>-15</code>.',
    'admin_adjust_balance_prompt': '<b>Adjust available balance</b>\n\nTarget: <b>{target}</b> · <code>{user_id}</code>\n\nSend a signed integer in XTR, for example <code>+100</code> or <code>-50</code>.',
    'admin_numeric_delta_invalid': 'Send a signed integer like +10 or -5.',
    'admin_risk_adjusted': 'Risk score updated.',
    'admin_balance_adjusted': 'Balance updated.',
    'admin_balance_adjust_invalid': 'Balance adjustment would make the balance negative.',
    'admin_logs_screen': '<b>Admin logs</b>\n\n{items}',
    'admin_logs_empty': '<b>Admin logs</b>\n\nNo admin actions yet.',
    'admin_log_row': '• {created} · admin {admin_id} · target {target_id} · {action} · {details}',
}

_STAGE7_TEXTS_RU = {
    'menu_admin': 'Админка',
    'blocked_screen': '<b>Доступ ограничен</b>\n\nВаш аккаунт временно заблокирован. Если это ошибка, напишите в поддержку: {support}',
    'blocked_alert': 'Ваш аккаунт заблокирован.',
    'proof_prompt': '<b>Подтверждение выполнения</b>\n\nОтправьте одним сообщением ссылку, @username, ID поста или краткое описание. Обычные задания автоматически уходят в холд, подозрительные — на ручную проверку.',
    'proof_sent_manual_review': 'Подтверждение получено. Задание отправлено на ручную проверку.',
    'task_detail_manual_review': 'на ручной проверке',
    'task_detail_rejected': 'отклонено',
    'admin_access_denied': 'Доступ к админке запрещён.',
    'admin_home_screen': '<b>Админка</b>\n\nВ очереди ручной проверки: <b>{queue}</b>\nЗаблокированных пользователей: <b>{blocked}</b>\nПользователей с высоким риском: <b>{high_risk}</b>\nВсего отклонённых выполнений: <b>{rejected}</b>',
    'admin_queue_button': 'Очередь проверок',
    'admin_logs_button': 'Логи админа',
    'admin_queue_empty': '<b>Очередь ручной проверки</b>\n\nСейчас очередь пуста.',
    'admin_queue_screen': '<b>Очередь ручной проверки</b>\n\n{items}',
    'admin_queue_line': '• #{submission_id} · {title} · {performer} · риск выполнения {risk} / риск пользователя {user_risk}',
    'admin_queue_row': '#{submission_id} · {title} · {performer} · Р{risk}',
    'admin_submission_not_found': 'Выполнение не найдено.',
    'admin_submission_already_reviewed': 'Это выполнение уже было обработано.',
    'admin_submission_screen': '<b>Выполнение #{submission_id}</b>\n\nКампания: <b>{title}</b>\nИсполнитель: <b>{performer}</b>\nID исполнителя: <code>{performer_id}</code>\nСтатус пользователя: <b>{user_status}</b>\nСтатус выполнения: <b>{submission_status}</b>\nНаграда: <b>{reward}</b> XTR\nРиск выполнения: <b>{submission_risk}</b>\nОбщий риск пользователя: <b>{user_risk}</b>\nОдобрено / отклонено / на ручной: <b>{approved}</b> / <b>{rejected}</b> / <b>{review_count}</b>\nОтправлено: <b>{submitted_at}</b>\nЦель: <code>{target}</code>\nПричина отклонения: <b>{reject_reason}</b>\n\n<b>Подтверждение</b>\n<blockquote>{proof}</blockquote>\n\n<b>Последние риск-события</b>\n{events}',
    'admin_risk_event_row': '• {created} · {event_type} · +{score}',
    'admin_risk_events_empty': 'Недавних риск-событий нет.',
    'admin_approve_button': 'Одобрить',
    'admin_reject_button': 'Отклонить',
    'admin_block_button': 'Заблокировать',
    'admin_unblock_button': 'Разблокировать',
    'admin_adjust_risk_button': 'Скорректировать риск',
    'admin_adjust_balance_button': 'Скорректировать баланс',
    'admin_submission_approved': 'Выполнение одобрено. Награда отправлена в холд.',
    'admin_submission_rejected': 'Выполнение отклонено.',
    'admin_reject_prompt': '<b>Отклонение выполнения #{submission_id}</b>\n\nОтправьте одним сообщением причину отклонения. Она сохранится в истории модерации.',
    'admin_reject_reason_empty': 'Причина отклонения не может быть пустой.',
    'admin_user_not_found': 'Пользователь не найден.',
    'admin_cannot_block_admin': 'Нельзя заблокировать другого администратора.',
    'admin_user_blocked': 'Пользователь заблокирован.',
    'admin_user_unblocked': 'Пользователь разблокирован.',
    'admin_adjust_risk_prompt': '<b>Корректировка risk score</b>\n\nЦель: <b>{target}</b> · <code>{user_id}</code>\nТекущий риск: <b>{current}</b>\n\nОтправьте целое число со знаком, например <code>+10</code> или <code>-15</code>.',
    'admin_adjust_balance_prompt': '<b>Корректировка доступного баланса</b>\n\nЦель: <b>{target}</b> · <code>{user_id}</code>\n\nОтправьте целое число со знаком в XTR, например <code>+100</code> или <code>-50</code>.',
    'admin_numeric_delta_invalid': 'Отправьте целое число со знаком, например +10 или -5.',
    'admin_risk_adjusted': 'Risk score обновлён.',
    'admin_balance_adjusted': 'Баланс обновлён.',
    'admin_balance_adjust_invalid': 'После корректировки баланс стал бы отрицательным.',
    'admin_logs_screen': '<b>Логи админа</b>\n\n{items}',
    'admin_logs_empty': '<b>Логи админа</b>\n\nАдмин-действий пока нет.',
    'admin_log_row': '• {created} · админ {admin_id} · цель {target_id} · {action} · {details}',
}

TEXTS['en'].update(_STAGE7_TEXTS_EN)
TEXTS['ru'].update(_STAGE7_TEXTS_RU)
for _lang, _mapping in TEXTS.items():
    if _lang not in {'ru', 'en'}:
        for _key, _value in _STAGE7_TEXTS_EN.items():
            _mapping.setdefault(_key, _value)
