LANGUAGES = {
    'ru': 'Русский',
    'en': 'English',
    'de': 'Deutsch',
    'es': 'Español',
    'pt': 'Português',
    'tr': 'Türkçe',
}

ROLE_PERFORMER = 'performer'
ROLE_CLIENT = 'client'

TEXTS = {
    'ru': {
        'welcome': 'Добро пожаловать в <b>{brand}</b>! Выберите язык.',
        'choose_role': 'Теперь выберите вашу роль.',
        'main_menu': 'Главное меню <b>{brand}</b>\n\nЯзык: <b>{language}</b>\nРоль: <b>{role}</b>',
        'performer': 'Исполнитель',
        'client': 'Заказчик',
        'menu_profile': 'Профиль',
        'menu_tasks': 'Задания',
        'menu_wallet': 'Кошелёк',
        'menu_history': 'История',
        'menu_campaigns': 'Кампании',
        'menu_stats': 'Аналитика',
        'menu_change_role': 'Сменить роль',
        'menu_change_language': 'Сменить язык',
        'back_to_language': 'Назад к языкам',
        'back_to_menu': 'В меню',
        'back_to_tasks': 'К заданиям',
        'refresh_screen': 'Обновить',
        'required_subscription_text': 'Чтобы продолжить, подпишитесь на обязательный чат и затем нажмите кнопку проверки.',
        'open_required_chat': 'Открыть чат',
        'open_required_chat_named': 'Открыть: {name}',
        'check_subscription': 'Проверить подписку',
        'subscription_missing': 'Сначала вступите в обязательный чат, затем повторите проверку.',
        'subscription_success': 'Подписка подтверждена.',
        'subscription_not_required_here': 'Внутри обязательного чата дополнительная проверка не нужна.',
        'subscription_check_unavailable': 'Автопроверка подписки сейчас недоступна. Бот продолжит работу без блокировки. Проверьте REQUIRED_CHAT_ID и права бота в чате.',
        'generic_ui_error': 'Произошла ошибка интерфейса. Экран обновлён.',
        'language_updated': 'Язык обновлён.',
        'role_updated': 'Роль обновлена.',
        'stale_screen': 'Этот экран уже неактуален. Используйте последнее сообщение бота.',
        'screen_refreshed': 'Экран обновлён.',
        'section_stub': '<b>{title}</b>\n\nРаздел подключён к общей навигации {brand}. Следующий этап наполнит его рабочей логикой.\n\nТекущая роль: <b>{role}</b>.',
        'profile_screen': '<b>Профиль исполнителя</b>\n\nID: <code>{profile_id}</code>\nРоль: <b>{role}</b>\nАктивных заданий: <b>{active_tasks}/{task_limit}</b>\nБаланс доступный: <b>{available}</b> XTR\nВ холде: <b>{hold}</b> XTR\nВсего заработано: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Доступные задания</b>\n\nАктивных сейчас: <b>{active_tasks}/{task_limit}</b>\nНиже показаны задания, которые ещё можно взять.',
        'tasks_empty': '<b>Доступные задания</b>\n\nСейчас новых заданий нет. Обновите экран позже.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nТип: <b>{task_type}</b>\nНаграда: <b>{reward}</b> XTR\nДоступно: <b>{remaining}</b>\n\nСтатус: <b>{status}</b>\n\nОткройте цель задания, затем возьмите его или отправьте подтверждение.',
        'task_detail_taken': 'взято',
        'task_detail_available': 'доступно',
        'task_detail_submitted': 'подтверждение уже отправлено',
        'open_task_target': 'Открыть цель задания',
        'take_task_button': 'Взять задание',
        'submit_task_button': 'Отправить на проверку',
        'open_task_submission': 'Вернуться к заданию',
        'cancel_proof_input': 'Отменить ввод',
        'task_taken': 'Задание взято. После выполнения отправьте подтверждение.',
        'task_not_found': 'Задание не найдено.',
        'task_not_available': 'Это задание сейчас недоступно.',
        'task_repeat_blocked': 'Повторное выполнение этого задания запрещено.',
        'task_limit_reached': 'Достигнут лимит активных заданий. Завершите текущие или ускорьте холд через VIP позже.',
        'proof_prompt': '<b>Подтверждение выполнения</b>\n\nОтправьте одним сообщением ссылку, @username, ID поста или краткое описание того, что вы сделали. После получения бот сразу начислит награду в холд.',
        'proof_empty': 'Подтверждение пустое. Отправьте текст одним сообщением.',
        'proof_accepted': 'Подтверждение принято. Награда начислена в холд.',
        'proof_already_sent': 'Подтверждение по этому заданию уже было отправлено.',
        'proof_input_cancelled': 'Ввод подтверждения отменён.',
        'wallet_screen': '<b>Кошелёк</b>\n\nДоступно: <b>{available}</b> XTR\nВ холде: <b>{hold}</b> XTR\nВнутренний баланс: <b>{internal}</b>\nВсего заработано: <b>{earned}</b> XTR\nВыведено: <b>{withdrawn}</b> XTR\nОсвобождено холдов сейчас: <b>{released}</b>',
        'history_screen': '<b>История операций</b>\n\n{items}',
        'history_empty': 'Операций пока нет.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Освобождено холдов: <b>{released}</b>.',
    },
    'en': {
        'welcome': 'Welcome to <b>{brand}</b>! Choose your language.',
        'choose_role': 'Now choose your role.',
        'main_menu': 'Main menu <b>{brand}</b>\n\nLanguage: <b>{language}</b>\nRole: <b>{role}</b>',
        'performer': 'Performer',
        'client': 'Client',
        'menu_profile': 'Profile',
        'menu_tasks': 'Tasks',
        'menu_wallet': 'Wallet',
        'menu_history': 'History',
        'menu_campaigns': 'Campaigns',
        'menu_stats': 'Analytics',
        'menu_change_role': 'Change role',
        'menu_change_language': 'Change language',
        'back_to_language': 'Back to languages',
        'back_to_menu': 'To menu',
        'back_to_tasks': 'Back to tasks',
        'refresh_screen': 'Refresh',
        'required_subscription_text': 'To continue, join the required chat and then press the verification button.',
        'open_required_chat': 'Open chat',
        'open_required_chat_named': 'Open: {name}',
        'check_subscription': 'Check subscription',
        'subscription_missing': 'Join the required chat first, then try the verification again.',
        'subscription_success': 'Subscription confirmed.',
        'subscription_not_required_here': 'Inside the required chat this check is not needed.',
        'subscription_check_unavailable': 'Automatic subscription check is unavailable right now. The bot will continue without blocking. Check REQUIRED_CHAT_ID and the bot permissions in the chat.',
        'generic_ui_error': 'An interface error occurred. The screen was refreshed.',
        'language_updated': 'Language updated.',
        'role_updated': 'Role updated.',
        'stale_screen': 'This screen is outdated. Use the latest bot message.',
        'screen_refreshed': 'Screen refreshed.',
        'section_stub': '<b>{title}</b>\n\nThis section is already wired into the shared {brand} navigation. A later stage will fill it with working logic.\n\nCurrent role: <b>{role}</b>.',
        'profile_screen': '<b>Performer profile</b>\n\nID: <code>{profile_id}</code>\nRole: <b>{role}</b>\nActive tasks: <b>{active_tasks}/{task_limit}</b>\nAvailable balance: <b>{available}</b> XTR\nIn hold: <b>{hold}</b> XTR\nLifetime earned: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Available tasks</b>\n\nActive now: <b>{active_tasks}/{task_limit}</b>\nTasks below can still be taken.',
        'tasks_empty': '<b>Available tasks</b>\n\nThere are no new tasks right now. Refresh later.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nType: <b>{task_type}</b>\nReward: <b>{reward}</b> XTR\nRemaining: <b>{remaining}</b>\n\nStatus: <b>{status}</b>\n\nOpen the target, then take the task or submit proof.',
        'task_detail_taken': 'taken',
        'task_detail_available': 'available',
        'task_detail_submitted': 'proof already sent',
        'open_task_target': 'Open task target',
        'take_task_button': 'Take task',
        'submit_task_button': 'Send for review',
        'open_task_submission': 'Back to task',
        'cancel_proof_input': 'Cancel input',
        'task_taken': 'Task taken. Send proof after completion.',
        'task_not_found': 'Task not found.',
        'task_not_available': 'This task is currently unavailable.',
        'task_repeat_blocked': 'Repeating this task is not allowed.',
        'task_limit_reached': 'You reached the active task limit. Finish current tasks first.',
        'proof_prompt': '<b>Task proof</b>\n\nSend one message with a link, @username, post ID or a short description of what you did. The reward will be placed into hold right away.',
        'proof_empty': 'Proof is empty. Send it as one text message.',
        'proof_accepted': 'Proof accepted. Reward placed into hold.',
        'proof_already_sent': 'Proof for this task has already been sent.',
        'proof_input_cancelled': 'Proof input cancelled.',
        'wallet_screen': '<b>Wallet</b>\n\nAvailable: <b>{available}</b> XTR\nIn hold: <b>{hold}</b> XTR\nInternal balance: <b>{internal}</b>\nLifetime earned: <b>{earned}</b> XTR\nWithdrawn: <b>{withdrawn}</b> XTR\nReleased now: <b>{released}</b>',
        'history_screen': '<b>Transaction history</b>\n\n{items}',
        'history_empty': 'No operations yet.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Released holds: <b>{released}</b>.',
    },
    'de': {
        'welcome': 'Willkommen bei <b>{brand}</b>! Wähle deine Sprache.',
        'choose_role': 'Wähle jetzt deine Rolle.',
        'main_menu': 'Hauptmenü <b>{brand}</b>\n\nSprache: <b>{language}</b>\nRolle: <b>{role}</b>',
        'performer': 'Ausführender',
        'client': 'Kunde',
        'menu_profile': 'Profil',
        'menu_tasks': 'Aufgaben',
        'menu_wallet': 'Wallet',
        'menu_history': 'Verlauf',
        'menu_campaigns': 'Kampagnen',
        'menu_stats': 'Analytik',
        'menu_change_role': 'Rolle ändern',
        'menu_change_language': 'Sprache ändern',
        'back_to_language': 'Zurück zu Sprachen',
        'back_to_menu': 'Zum Menü',
        'back_to_tasks': 'Zu Aufgaben',
        'refresh_screen': 'Aktualisieren',
        'required_subscription_text': 'Um fortzufahren, tritt dem Pflicht-Chat bei und drücke dann auf die Prüftaste.',
        'open_required_chat': 'Chat öffnen',
        'check_subscription': 'Abo prüfen',
        'subscription_missing': 'Bitte tritt zuerst dem Pflicht-Chat bei und versuche die Prüfung erneut.',
        'subscription_success': 'Abo bestätigt.',
        'subscription_not_required_here': 'Innerhalb des Pflicht-Chats ist diese Prüfung nicht nötig.',
        'subscription_check_unavailable': 'Die automatische Abo-Prüfung ist derzeit nicht verfügbar. Der Bot blockiert dich nicht. Prüfe REQUIRED_CHAT_ID und die Rechte des Bots im Chat.',
        'generic_ui_error': 'Ein Oberflächenfehler ist aufgetreten. Der Bildschirm wurde aktualisiert.',
        'language_updated': 'Sprache aktualisiert.',
        'role_updated': 'Rolle aktualisiert.',
        'stale_screen': 'Dieser Bildschirm ist veraltet. Nutze die letzte Bot-Nachricht.',
        'screen_refreshed': 'Bildschirm aktualisiert.',
        'section_stub': '<b>{title}</b>\n\nDieser Bereich ist bereits an die gemeinsame Navigation von {brand} angeschlossen. In einer späteren Phase kommt die Arbeitslogik hinzu.\n\nAktuelle Rolle: <b>{role}</b>.',
        'profile_screen': '<b>Ausführenden-Profil</b>\n\nID: <code>{profile_id}</code>\nRolle: <b>{role}</b>\nAktive Aufgaben: <b>{active_tasks}/{task_limit}</b>\nVerfügbar: <b>{available}</b> XTR\nIm Hold: <b>{hold}</b> XTR\nGesamt verdient: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Verfügbare Aufgaben</b>\n\nAktiv jetzt: <b>{active_tasks}/{task_limit}</b>\nDie folgenden Aufgaben können noch übernommen werden.',
        'tasks_empty': '<b>Verfügbare Aufgaben</b>\n\nIm Moment gibt es keine neuen Aufgaben.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nTyp: <b>{task_type}</b>\nBelohnung: <b>{reward}</b> XTR\nVerbleibend: <b>{remaining}</b>\n\nStatus: <b>{status}</b>\n\nÖffne das Ziel und übernimm die Aufgabe oder sende den Nachweis.',
        'task_detail_taken': 'übernommen',
        'task_detail_available': 'verfügbar',
        'task_detail_submitted': 'Nachweis bereits gesendet',
        'open_task_target': 'Ziel öffnen',
        'take_task_button': 'Aufgabe übernehmen',
        'submit_task_button': 'Zur Prüfung senden',
        'open_task_submission': 'Zurück zur Aufgabe',
        'cancel_proof_input': 'Eingabe abbrechen',
        'task_taken': 'Aufgabe übernommen. Sende danach den Nachweis.',
        'task_not_found': 'Aufgabe nicht gefunden.',
        'task_not_available': 'Diese Aufgabe ist derzeit nicht verfügbar.',
        'task_repeat_blocked': 'Diese Aufgabe darf nicht wiederholt werden.',
        'task_limit_reached': 'Limit aktiver Aufgaben erreicht.',
        'proof_prompt': '<b>Nachweis</b>\n\nSende eine Nachricht mit Link, @username, Post-ID oder kurzer Beschreibung. Die Belohnung geht sofort in den Hold.',
        'proof_empty': 'Der Nachweis ist leer.',
        'proof_accepted': 'Nachweis akzeptiert. Belohnung im Hold.',
        'proof_already_sent': 'Der Nachweis wurde bereits gesendet.',
        'proof_input_cancelled': 'Eingabe abgebrochen.',
        'wallet_screen': '<b>Wallet</b>\n\nVerfügbar: <b>{available}</b> XTR\nIm Hold: <b>{hold}</b> XTR\nInternes Guthaben: <b>{internal}</b>\nGesamt verdient: <b>{earned}</b> XTR\nAusgezahlt: <b>{withdrawn}</b> XTR\nJetzt freigegeben: <b>{released}</b>',
        'history_screen': '<b>Transaktionsverlauf</b>\n\n{items}',
        'history_empty': 'Noch keine Vorgänge.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Freigegebene Holds: <b>{released}</b>.',
    },
    'es': {
        'welcome': 'Bienvenido a <b>{brand}</b>. Elige tu idioma.',
        'choose_role': 'Ahora elige tu rol.',
        'main_menu': 'Menú principal <b>{brand}</b>\n\nIdioma: <b>{language}</b>\nRol: <b>{role}</b>',
        'performer': 'Ejecutor',
        'client': 'Cliente',
        'menu_profile': 'Perfil',
        'menu_tasks': 'Tareas',
        'menu_wallet': 'Billetera',
        'menu_history': 'Historial',
        'menu_campaigns': 'Campañas',
        'menu_stats': 'Analítica',
        'menu_change_role': 'Cambiar rol',
        'menu_change_language': 'Cambiar idioma',
        'back_to_language': 'Volver a idiomas',
        'back_to_menu': 'Al menú',
        'back_to_tasks': 'A tareas',
        'refresh_screen': 'Actualizar',
        'required_subscription_text': 'Para continuar, únete al chat obligatorio y luego pulsa el botón de verificación.',
        'open_required_chat': 'Abrir chat',
        'check_subscription': 'Verificar suscripción',
        'subscription_missing': 'Primero únete al chat obligatorio y luego repite la verificación.',
        'subscription_success': 'Suscripción confirmada.',
        'subscription_not_required_here': 'Dentro del chat obligatorio no hace falta esta comprobación.',
        'subscription_check_unavailable': 'La verificación automática de la suscripción no está disponible ahora. El bot seguirá funcionando sin bloquearte. Revisa REQUIRED_CHAT_ID y los permisos del bot en el chat.',
        'generic_ui_error': 'Se produjo un error de interfaz. La pantalla se actualizó.',
        'language_updated': 'Idioma actualizado.',
        'role_updated': 'Rol actualizado.',
        'stale_screen': 'Esta pantalla ya no es válida. Usa el último mensaje del bot.',
        'screen_refreshed': 'Pantalla actualizada.',
        'section_stub': '<b>{title}</b>\n\nEsta sección ya está conectada a la navegación compartida de {brand}. En una etapa posterior recibirá la lógica funcional.\n\nRol actual: <b>{role}</b>.',
        'profile_screen': '<b>Perfil del ejecutor</b>\n\nID: <code>{profile_id}</code>\nRol: <b>{role}</b>\nTareas activas: <b>{active_tasks}/{task_limit}</b>\nDisponible: <b>{available}</b> XTR\nEn retención: <b>{hold}</b> XTR\nGanado total: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Tareas disponibles</b>\n\nActivas ahora: <b>{active_tasks}/{task_limit}</b>\nLas tareas siguientes aún se pueden tomar.',
        'tasks_empty': '<b>Tareas disponibles</b>\n\nAhora no hay tareas nuevas.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nTipo: <b>{task_type}</b>\nRecompensa: <b>{reward}</b> XTR\nRestantes: <b>{remaining}</b>\n\nEstado: <b>{status}</b>\n\nAbre el objetivo y luego toma la tarea o envía la prueba.',
        'task_detail_taken': 'tomada',
        'task_detail_available': 'disponible',
        'task_detail_submitted': 'prueba ya enviada',
        'open_task_target': 'Abrir objetivo',
        'take_task_button': 'Tomar tarea',
        'submit_task_button': 'Enviar a revisión',
        'open_task_submission': 'Volver a la tarea',
        'cancel_proof_input': 'Cancelar entrada',
        'task_taken': 'Tarea tomada. Envía la prueba después.',
        'task_not_found': 'Tarea no encontrada.',
        'task_not_available': 'Esta tarea no está disponible ahora.',
        'task_repeat_blocked': 'No se permite repetir esta tarea.',
        'task_limit_reached': 'Se alcanzó el límite de tareas activas.',
        'proof_prompt': '<b>Prueba de tarea</b>\n\nEnvía un mensaje con enlace, @usuario, ID de publicación o una breve descripción. La recompensa irá a retención de inmediato.',
        'proof_empty': 'La prueba está vacía.',
        'proof_accepted': 'Prueba aceptada. Recompensa en retención.',
        'proof_already_sent': 'La prueba ya fue enviada.',
        'proof_input_cancelled': 'Entrada cancelada.',
        'wallet_screen': '<b>Billetera</b>\n\nDisponible: <b>{available}</b> XTR\nEn retención: <b>{hold}</b> XTR\nSaldo interno: <b>{internal}</b>\nGanado total: <b>{earned}</b> XTR\nRetirado: <b>{withdrawn}</b> XTR\nLiberado ahora: <b>{released}</b>',
        'history_screen': '<b>Historial de operaciones</b>\n\n{items}',
        'history_empty': 'Aún no hay operaciones.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Retenciones liberadas: <b>{released}</b>.',
    },
    'pt': {
        'welcome': 'Bem-vindo ao <b>{brand}</b>! Escolha seu idioma.',
        'choose_role': 'Agora escolha seu papel.',
        'main_menu': 'Menu principal <b>{brand}</b>\n\nIdioma: <b>{language}</b>\nPapel: <b>{role}</b>',
        'performer': 'Executor',
        'client': 'Cliente',
        'menu_profile': 'Perfil',
        'menu_tasks': 'Tarefas',
        'menu_wallet': 'Carteira',
        'menu_history': 'Histórico',
        'menu_campaigns': 'Campanhas',
        'menu_stats': 'Análises',
        'menu_change_role': 'Trocar papel',
        'menu_change_language': 'Trocar idioma',
        'back_to_language': 'Voltar aos idiomas',
        'back_to_menu': 'Ao menu',
        'back_to_tasks': 'Para tarefas',
        'refresh_screen': 'Atualizar',
        'required_subscription_text': 'Para continuar, entre no chat obrigatório e depois pressione o botão de verificação.',
        'open_required_chat': 'Abrir chat',
        'check_subscription': 'Verificar inscrição',
        'subscription_missing': 'Entre primeiro no chat obrigatório e depois tente a verificação novamente.',
        'subscription_success': 'Inscrição confirmada.',
        'subscription_not_required_here': 'Dentro do chat obrigatório essa verificação não é necessária.',
        'subscription_check_unavailable': 'A verificação automática da inscrição não está disponível agora. O bot continuará sem bloquear você. Verifique REQUIRED_CHAT_ID e as permissões do bot no chat.',
        'generic_ui_error': 'Ocorreu um erro de interface. A tela foi atualizada.',
        'language_updated': 'Idioma atualizado.',
        'role_updated': 'Papel atualizado.',
        'stale_screen': 'Esta tela já está desatualizada. Use a mensagem mais recente do bot.',
        'screen_refreshed': 'Tela atualizada.',
        'section_stub': '<b>{title}</b>\n\nEsta seção já está ligada à navegação compartilhada do {brand}. Uma etapa posterior adicionará a lógica funcional.\n\nPapel atual: <b>{role}</b>.',
        'profile_screen': '<b>Perfil do executor</b>\n\nID: <code>{profile_id}</code>\nPapel: <b>{role}</b>\nTarefas ativas: <b>{active_tasks}/{task_limit}</b>\nDisponível: <b>{available}</b> XTR\nEm hold: <b>{hold}</b> XTR\nTotal ganho: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Tarefas disponíveis</b>\n\nAtivas agora: <b>{active_tasks}/{task_limit}</b>\nAs tarefas abaixo ainda podem ser aceitas.',
        'tasks_empty': '<b>Tarefas disponíveis</b>\n\nNão há novas tarefas agora.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nTipo: <b>{task_type}</b>\nRecompensa: <b>{reward}</b> XTR\nRestantes: <b>{remaining}</b>\n\nStatus: <b>{status}</b>\n\nAbra o alvo e depois aceite a tarefa ou envie a prova.',
        'task_detail_taken': 'aceita',
        'task_detail_available': 'disponível',
        'task_detail_submitted': 'prova já enviada',
        'open_task_target': 'Abrir alvo',
        'take_task_button': 'Aceitar tarefa',
        'submit_task_button': 'Enviar para revisão',
        'open_task_submission': 'Voltar à tarefa',
        'cancel_proof_input': 'Cancelar entrada',
        'task_taken': 'Tarefa aceita. Envie a prova depois.',
        'task_not_found': 'Tarefa não encontrada.',
        'task_not_available': 'Esta tarefa não está disponível agora.',
        'task_repeat_blocked': 'Não é permitido repetir esta tarefa.',
        'task_limit_reached': 'O limite de tarefas ativas foi atingido.',
        'proof_prompt': '<b>Prova da tarefa</b>\n\nEnvie uma mensagem com link, @usuário, ID do post ou uma breve descrição. A recompensa vai para hold imediatamente.',
        'proof_empty': 'A prova está vazia.',
        'proof_accepted': 'Prova aceita. Recompensa em hold.',
        'proof_already_sent': 'A prova já foi enviada.',
        'proof_input_cancelled': 'Entrada cancelada.',
        'wallet_screen': '<b>Carteira</b>\n\nDisponível: <b>{available}</b> XTR\nEm hold: <b>{hold}</b> XTR\nSaldo interno: <b>{internal}</b>\nTotal ganho: <b>{earned}</b> XTR\nRetirado: <b>{withdrawn}</b> XTR\nLiberado agora: <b>{released}</b>',
        'history_screen': '<b>Histórico de operações</b>\n\n{items}',
        'history_empty': 'Ainda não há operações.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Holds liberados: <b>{released}</b>.',
    },
    'tr': {
        'welcome': '<b>{brand}</b>\'a hoş geldin! Dilini seç.',
        'choose_role': 'Şimdi rolünü seç.',
        'main_menu': 'Ana menü <b>{brand}</b>\n\nDil: <b>{language}</b>\nRol: <b>{role}</b>',
        'performer': 'Görev yapan',
        'client': 'Müşteri',
        'menu_profile': 'Profil',
        'menu_tasks': 'Görevler',
        'menu_wallet': 'Cüzdan',
        'menu_history': 'Geçmiş',
        'menu_campaigns': 'Kampanyalar',
        'menu_stats': 'Analitik',
        'menu_change_role': 'Rol değiştir',
        'menu_change_language': 'Dil değiştir',
        'back_to_language': 'Dillere dön',
        'back_to_menu': 'Menüye dön',
        'back_to_tasks': 'Görevlere dön',
        'refresh_screen': 'Yenile',
        'required_subscription_text': 'Devam etmek için zorunlu sohbete katıl ve sonra doğrulama düğmesine bas.',
        'open_required_chat': 'Sohbeti aç',
        'check_subscription': 'Aboneliği kontrol et',
        'subscription_missing': 'Önce zorunlu sohbete katıl, sonra doğrulamayı tekrar dene.',
        'subscription_success': 'Abonelik doğrulandı.',
        'subscription_not_required_here': 'Zorunlu sohbetin içinde bu kontrol gerekli değil.',
        'subscription_check_unavailable': 'Otomatik abonelik kontrolü şu anda kullanılamıyor. Bot seni engellemeden çalışmaya devam edecek. REQUIRED_CHAT_ID değerini ve botun sohbetteki izinlerini kontrol et.',
        'generic_ui_error': 'Bir arayüz hatası oluştu. Ekran yenilendi.',
        'language_updated': 'Dil güncellendi.',
        'role_updated': 'Rol güncellendi.',
        'stale_screen': 'Bu ekran artık geçersiz. Botun son mesajını kullan.',
        'screen_refreshed': 'Ekran yenilendi.',
        'section_stub': '<b>{title}</b>\n\nBu bölüm zaten {brand} ortak gezintisine bağlandı. Sonraki bir aşama çalışan mantığı ekleyecek.\n\nGeçerli rol: <b>{role}</b>.',
        'profile_screen': '<b>Görev yapan profili</b>\n\nID: <code>{profile_id}</code>\nRol: <b>{role}</b>\nAktif görevler: <b>{active_tasks}/{task_limit}</b>\nKullanılabilir bakiye: <b>{available}</b> XTR\nHold bakiyesi: <b>{hold}</b> XTR\nToplam kazanç: <b>{earned}</b> XTR',
        'tasks_screen': '<b>Uygun görevler</b>\n\nŞu an aktif: <b>{active_tasks}/{task_limit}</b>\nAşağıdaki görevler hâlâ alınabilir.',
        'tasks_empty': '<b>Uygun görevler</b>\n\nŞu anda yeni görev yok.',
        'task_row': '• {title} · {reward} XTR',
        'task_detail': '<b>{title}</b>\n\nTür: <b>{task_type}</b>\nÖdül: <b>{reward}</b> XTR\nKalan: <b>{remaining}</b>\n\nDurum: <b>{status}</b>\n\nHedefi aç, sonra görevi al veya kanıtı gönder.',
        'task_detail_taken': 'alındı',
        'task_detail_available': 'uygun',
        'task_detail_submitted': 'kanıt zaten gönderildi',
        'open_task_target': 'Görev hedefini aç',
        'take_task_button': 'Görevi al',
        'submit_task_button': 'İncelemeye gönder',
        'open_task_submission': 'Göreve dön',
        'cancel_proof_input': 'Girişi iptal et',
        'task_taken': 'Görev alındı. Tamamlayınca kanıt gönder.',
        'task_not_found': 'Görev bulunamadı.',
        'task_not_available': 'Bu görev şu anda uygun değil.',
        'task_repeat_blocked': 'Bu görevi tekrar yapmak yasak.',
        'task_limit_reached': 'Aktif görev limiti doldu.',
        'proof_prompt': '<b>Görev kanıtı</b>\n\nBağlantı, @kullanıcı, gönderi kimliği veya kısa açıklama içeren tek mesaj gönder. Ödül hemen hold bakiyesine eklenir.',
        'proof_empty': 'Kanıt boş.',
        'proof_accepted': 'Kanıt kabul edildi. Ödül hold bakiyesine eklendi.',
        'proof_already_sent': 'Bu görev için kanıt zaten gönderildi.',
        'proof_input_cancelled': 'Girdi iptal edildi.',
        'wallet_screen': '<b>Cüzdan</b>\n\nKullanılabilir: <b>{available}</b> XTR\nHold: <b>{hold}</b> XTR\nİç bakiye: <b>{internal}</b>\nToplam kazanç: <b>{earned}</b> XTR\nÇekilen: <b>{withdrawn}</b> XTR\nŞimdi açılan: <b>{released}</b>',
        'history_screen': '<b>İşlem geçmişi</b>\n\n{items}',
        'history_empty': 'Henüz işlem yok.',
        'history_row': '• {date} · {entry_type} · {amount} XTR · {status}',
        'released_notice': 'Açılan holdlar: <b>{released}</b>.',
    },
}


_STAGE5_TEXTS_EN = {
    'campaign_client_only': 'This section is available only for the client role.',
    'campaigns_screen': '<b>Your campaigns</b>\n\nTotal: <b>{total}</b>\nActive: <b>{active}</b>\nPaused: <b>{paused}</b>\nDrafts: <b>{drafts}</b>\n\nOpen a card below or create a new campaign.',
    'campaigns_empty': '<b>Your campaigns</b>\n\nThere are no campaigns yet. Create the first one below.',
    'campaign_create_button': 'Create campaign',
    'back_to_campaigns': 'Back to campaigns',
    'campaign_row': 'Campaign #{campaign_id} · {title} · {status}',
    'campaign_create_intro': '<b>Create campaign</b>\n\nChoose a task type for the new campaign.',
    'campaign_type_saved': 'Task type selected.',
    'campaign_task_type_channel_subscribe': 'Subscribe to channel',
    'campaign_task_type_chat_join': 'Join chat',
    'campaign_task_type_post_view': 'View post',
    'campaign_task_type_bot_start': 'Start bot',
    'campaign_task_type_mini_app_open': 'Open Mini App',
    'campaign_input_screen': '<b>Campaign setup</b>\n\nType: <b>{task_type}</b>\nTarget: <code>{target_url}</code>\nReward: <b>{reward}</b> XTR\nQuantity: <b>{quantity}</b>\n\n{step}',
    'campaign_target_prompt': 'Send the target link or @username in one message.',
    'campaign_reward_prompt': 'Send the reward per completion as a whole number in Sparks✨.',
    'campaign_quantity_prompt': 'Send the number of required completions as a whole number.',
    'campaign_target_saved': 'Target saved.',
    'campaign_reward_saved': 'Reward saved.',
    'campaign_quantity_saved': 'Quantity saved. Check the preview below.',
    'campaign_target_invalid': 'Target is invalid. Send a valid Telegram or web link.',
    'campaign_reward_invalid': 'Reward must be a positive whole number from 1 to 100000.',
    'campaign_quantity_invalid': 'Quantity must be a positive whole number from 1 to 100000.',
    'campaign_invalid_task_type': 'Unsupported task type.',
    'campaign_draft_missing': 'Campaign draft was not found. Start creation again.',
    'campaign_preview_screen': '<b>Campaign preview</b>\n\nType: <b>{task_type}</b>\nTarget: <code>{target_url}</code>\nReward: <b>{reward}</b> XTR\nQuantity: <b>{quantity}</b>\nBudget: <b>{budget}</b> XTR\n\nSave as draft or launch immediately.',
    'campaign_save_draft_button': 'Save draft',
    'campaign_launch_now_button': 'Launch now',
    'campaign_cancel_button': 'Cancel',
    'campaign_create_cancelled': 'Campaign creation cancelled.',
    'campaign_created_draft': 'Campaign saved as draft.',
    'campaign_created_active': 'Campaign created and launched.',
    'campaign_card_screen': '<b>Campaign #{campaign_id}</b>\n\nTitle: <b>{title}</b>\nType: <b>{task_type}</b>\nTarget: <code>{target_url}</code>\nReward: <b>{reward}</b> XTR\nQuantity: <b>{quantity}</b>\nCompleted: <b>{completed}</b>\nRejected: <b>{rejected}</b>\nBudget: <b>{budget_total}</b> XTR\nSpent: <b>{budget_spent}</b> XTR\nReserved: <b>{budget_reserved}</b> XTR\nRemaining: <b>{budget_remaining}</b> XTR\nStatus: <b>{status}</b>',
    'campaign_not_found': 'Campaign not found.',
    'campaign_status_draft': 'draft',
    'campaign_status_active': 'active',
    'campaign_status_paused': 'paused',
    'campaign_status_completed': 'completed',
    'campaign_status_archived': 'archived',
    'campaign_launch_button': 'Launch campaign',
    'campaign_pause_button': 'Pause campaign',
    'campaign_resume_button': 'Resume campaign',
    'campaign_launched': 'Campaign launched.',
    'campaign_paused': 'Campaign paused.',
    'campaign_resumed': 'Campaign resumed.',
    'campaign_status_invalid': 'Unsupported campaign status.',
    'campaign_status_transition_invalid': 'This status change is not allowed right now.',
    'campaign_stats_screen': '<b>Campaign analytics</b>\n\nTotal campaigns: <b>{total}</b>\nActive: <b>{active}</b>\nPaused: <b>{paused}</b>\nDrafts: <b>{drafts}</b>\nCompleted actions: <b>{completed}</b>\nRejected actions: <b>{rejected}</b>\nTotal budget: <b>{budget}</b> XTR\nSpent: <b>{spent}</b> XTR\nReserved: <b>{reserved}</b> XTR\nRemaining: <b>{remaining}</b> XTR',
}

_STAGE5_TEXTS_RU = {
    'campaign_client_only': 'Этот раздел доступен только для роли заказчика.',
    'campaigns_screen': '<b>Ваши кампании</b>\n\nВсего: <b>{total}</b>\nАктивных: <b>{active}</b>\nНа паузе: <b>{paused}</b>\nЧерновиков: <b>{drafts}</b>\n\nОткройте карточку ниже или создайте новую кампанию.',
    'campaigns_empty': '<b>Ваши кампании</b>\n\nПока нет ни одной кампании. Ниже можно создать первую.',
    'campaign_create_button': 'Создать кампанию',
    'back_to_campaigns': 'К кампаниям',
    'campaign_row': 'Кампания #{campaign_id} · {title} · {status}',
    'campaign_create_intro': '<b>Создание кампании</b>\n\nВыберите тип задания для новой кампании.',
    'campaign_type_saved': 'Тип задания выбран.',
    'campaign_task_type_channel_subscribe': 'Подписка на канал',
    'campaign_task_type_chat_join': 'Вступление в чат',
    'campaign_task_type_post_view': 'Просмотр поста',
    'campaign_task_type_bot_start': 'Запуск бота',
    'campaign_task_type_mini_app_open': 'Открытие Mini App',
    'campaign_input_screen': '<b>Настройка кампании</b>\n\nТип: <b>{task_type}</b>\nЦель: <code>{target_url}</code>\nНаграда: <b>{reward}</b> XTR\nКоличество: <b>{quantity}</b>\n\n{step}',
    'campaign_target_prompt': 'Отправьте ссылку на цель или @username одним сообщением.',
    'campaign_reward_prompt': 'Отправьте награду за одно выполнение целым числом в Искрах✨.',
    'campaign_quantity_prompt': 'Отправьте нужное количество выполнений целым числом.',
    'campaign_target_saved': 'Цель сохранена.',
    'campaign_reward_saved': 'Награда сохранена.',
    'campaign_quantity_saved': 'Количество сохранено. Проверьте предпросмотр ниже.',
    'campaign_target_invalid': 'Цель указана неверно. Отправьте корректную ссылку Telegram или web.',
    'campaign_reward_invalid': 'Награда должна быть положительным целым числом от 1 до 100000.',
    'campaign_quantity_invalid': 'Количество должно быть положительным целым числом от 1 до 100000.',
    'campaign_invalid_task_type': 'Неподдерживаемый тип задания.',
    'campaign_draft_missing': 'Черновик кампании не найден. Начните создание заново.',
    'campaign_preview_screen': '<b>Предпросмотр кампании</b>\n\nТип: <b>{task_type}</b>\nЦель: <code>{target_url}</code>\nНаграда: <b>{reward}</b> XTR\nКоличество: <b>{quantity}</b>\nБюджет: <b>{budget}</b> XTR\n\nСохраните как черновик или запустите сразу.',
    'campaign_save_draft_button': 'Сохранить черновик',
    'campaign_launch_now_button': 'Запустить сразу',
    'campaign_cancel_button': 'Отменить',
    'campaign_create_cancelled': 'Создание кампании отменено.',
    'campaign_created_draft': 'Кампания сохранена как черновик.',
    'campaign_created_active': 'Кампания создана и запущена.',
    'campaign_card_screen': '<b>Кампания #{campaign_id}</b>\n\nНазвание: <b>{title}</b>\nТип: <b>{task_type}</b>\nЦель: <code>{target_url}</code>\nНаграда: <b>{reward}</b> XTR\nКоличество: <b>{quantity}</b>\nВыполнено: <b>{completed}</b>\nОтклонено: <b>{rejected}</b>\nБюджет: <b>{budget_total}</b> XTR\nПотрачено: <b>{budget_spent}</b> XTR\nВ резерве: <b>{budget_reserved}</b> XTR\nОстаток: <b>{budget_remaining}</b> XTR\nСтатус: <b>{status}</b>',
    'campaign_not_found': 'Кампания не найдена.',
    'campaign_status_draft': 'черновик',
    'campaign_status_active': 'активна',
    'campaign_status_paused': 'на паузе',
    'campaign_status_completed': 'завершена',
    'campaign_status_archived': 'в архиве',
    'campaign_launch_button': 'Запустить кампанию',
    'campaign_pause_button': 'Поставить на паузу',
    'campaign_resume_button': 'Возобновить кампанию',
    'campaign_launched': 'Кампания запущена.',
    'campaign_paused': 'Кампания поставлена на паузу.',
    'campaign_resumed': 'Кампания возобновлена.',
    'campaign_status_invalid': 'Неподдерживаемый статус кампании.',
    'campaign_status_transition_invalid': 'Сейчас такое изменение статуса недоступно.',
    'campaign_stats_screen': '<b>Аналитика кампаний</b>\n\nВсего кампаний: <b>{total}</b>\nАктивных: <b>{active}</b>\nНа паузе: <b>{paused}</b>\nЧерновиков: <b>{drafts}</b>\nВыполненных действий: <b>{completed}</b>\nОтклонённых действий: <b>{rejected}</b>\nОбщий бюджет: <b>{budget}</b> XTR\nПотрачено: <b>{spent}</b> XTR\nВ резерве: <b>{reserved}</b> XTR\nОстаток: <b>{remaining}</b> XTR',
}

TEXTS['en'].update(_STAGE5_TEXTS_EN)
TEXTS['ru'].update(_STAGE5_TEXTS_RU)
for _lang, _mapping in TEXTS.items():
    if _lang not in {'ru', 'en'}:
        for _key, _value in _STAGE5_TEXTS_EN.items():
            _mapping.setdefault(_key, _value)

_STAGE6_TEXTS_EN = {
    'menu_vip': 'VIP',
    'menu_rewards': 'Rewards',
    'menu_referrals': 'Referrals',
    'internal_currency_name': 'Boosts',
    'wallet_screen': '<b>Wallet</b>\n\nAvailable: <b>{available}</b> XTR\nIn hold: <b>{hold}</b> XTR\n{internal_name}: <b>{internal}</b>\nLifetime earned: <b>{earned}</b> XTR\nWithdrawn: <b>{withdrawn}</b> XTR\nReleased now: <b>{released}</b>',
    'history_row': '• {date} · {entry_type} · {amount} {currency} · {status}',
    'vip_screen': '<b>VIP center</b>\n\n{active_block}\n\nTotal bonuses now:\n• Hold speed: <b>{hold_speed}%</b>\n• Active task slots: <b>+{task_bonus}</b>\n• Queue priority: <b>{priority}</b>\n• Referral rate bonus: <b>+{ref_bonus}%</b>\n\nBuy a plan with {internal_name}.',
    'vip_no_active': 'No active VIP plans yet.',
    'vip_active_row': '• {title} — until <b>{expires_at}</b>',
    'vip_plan_7_title': 'VIP 7 days',
    'vip_plan_7_desc': '25% faster hold, +2 active tasks, queue priority 1, +2% referral rate.',
    'vip_plan_30_title': 'VIP 30 days',
    'vip_plan_30_desc': '50% faster hold, +5 active tasks, queue priority 2, +5% referral rate.',
    'vip_buy_button': 'Buy for {price} {internal_name}',
    'vip_plan_not_found': 'VIP plan not found.',
    'vip_balance_low': 'Not enough internal balance for this VIP plan.',
    'vip_purchase_success': 'VIP plan activated.',
    'rewards_screen': '<b>Rewards catalog</b>\n\nSpend {internal_name} on utility bonuses.\nCurrent balance: <b>{balance}</b> {internal_name}\n\nAvailable items:\n{items}',
    'reward_item_row': '• <b>{title}</b> — {price} {internal_name}\n{desc}',
    'reward_hold_boost_title': 'Speed booster · 3 days',
    'reward_hold_boost_desc': 'Extra 15% hold acceleration for 3 days.',
    'reward_slots_boost_title': 'Slot booster · 3 days',
    'reward_slots_boost_desc': 'Adds +1 active task slot for 3 days.',
    'reward_priority_boost_title': 'Priority booster · 3 days',
    'reward_priority_boost_desc': 'Priority queue level 1 and +1% referral rate for 3 days.',
    'reward_buy_button': 'Buy bonus',
    'reward_item_not_found': 'Reward item not found.',
    'reward_balance_low': 'Not enough internal balance for this bonus.',
    'reward_purchase_success': 'Bonus activated.',
    'rewards_claim_demo_button': 'Claim demo top up',
    'demo_topup_success': 'Demo top up credited to internal balance.',
    'demo_topup_disabled': 'Demo top up is disabled.',
    'demo_topup_already_claimed': 'Demo top up has already been claimed.',
    'referrals_screen': '<b>Referrals</b>\n\nYour link:\n<code>{link}</code>\n\nInvited: <b>{count}</b>\nEarned: <b>{earned}</b> {internal_name}\nCurrent referral rate: <b>{rate}%</b>\n\n{items}',
    'referrals_empty': 'No invited users yet. Share your link to start earning.',
    'referral_row': '• {name} — earned: <b>{earned}</b> {internal_name} · joined: <b>{joined}</b>',
}

_STAGE6_TEXTS_RU = {
    'menu_vip': 'VIP',
    'menu_rewards': 'Награды',
    'menu_referrals': 'Рефералы',
    'internal_currency_name': 'Бусты',
    'wallet_screen': '<b>Кошелёк</b>\n\nДоступно: <b>{available}</b> XTR\nВ холде: <b>{hold}</b> XTR\n{internal_name}: <b>{internal}</b>\nВсего заработано: <b>{earned}</b> XTR\nВыведено: <b>{withdrawn}</b> XTR\nОсвобождено холдов сейчас: <b>{released}</b>',
    'history_row': '• {date} · {entry_type} · {amount} {currency} · {status}',
    'vip_screen': '<b>VIP-центр</b>\n\n{active_block}\n\nСуммарные бонусы сейчас:\n• Ускорение холда: <b>{hold_speed}%</b>\n• Доп. лимит активных заданий: <b>+{task_bonus}</b>\n• Приоритет очереди: <b>{priority}</b>\n• Бонус к реферальной ставке: <b>+{ref_bonus}%</b>\n\nПокупайте планы за {internal_name}.',
    'vip_no_active': 'Активных VIP-планов пока нет.',
    'vip_active_row': '• {title} — действует до <b>{expires_at}</b>',
    'vip_plan_7_title': 'VIP на 7 дней',
    'vip_plan_7_desc': 'Холд быстрее на 25%, +2 активных задания, приоритет 1, +2% к реферальной ставке.',
    'vip_plan_30_title': 'VIP на 30 дней',
    'vip_plan_30_desc': 'Холд быстрее на 50%, +5 активных заданий, приоритет 2, +5% к реферальной ставке.',
    'vip_buy_button': 'Купить за {price} {internal_name}',
    'vip_plan_not_found': 'VIP-план не найден.',
    'vip_balance_low': 'Недостаточно внутренней валюты для покупки VIP.',
    'vip_purchase_success': 'VIP-план активирован.',
    'rewards_screen': '<b>Каталог наград</b>\n\nТратьте {internal_name} на полезные бонусы.\nТекущий баланс: <b>{balance}</b> {internal_name}\n\nДоступные бонусы:\n{items}',
    'reward_item_row': '• <b>{title}</b> — {price} {internal_name}\n{desc}',
    'reward_hold_boost_title': 'Ускоритель холда · 3 дня',
    'reward_hold_boost_desc': 'Дополнительное ускорение холда на 15% на 3 дня.',
    'reward_slots_boost_title': 'Слоты заданий · 3 дня',
    'reward_slots_boost_desc': 'Добавляет +1 активный слот заданий на 3 дня.',
    'reward_priority_boost_title': 'Приоритет · 3 дня',
    'reward_priority_boost_desc': 'Приоритет очереди 1 и +1% к реферальной ставке на 3 дня.',
    'reward_buy_button': 'Купить бонус',
    'reward_item_not_found': 'Такой бонус не найден.',
    'reward_balance_low': 'Недостаточно внутренней валюты для покупки бонуса.',
    'reward_purchase_success': 'Бонус активирован.',
    'rewards_claim_demo_button': 'Получить демо-пополнение',
    'demo_topup_success': 'Демо-пополнение зачислено на внутренний баланс.',
    'demo_topup_disabled': 'Демо-пополнение отключено.',
    'demo_topup_already_claimed': 'Демо-пополнение уже было получено.',
    'referrals_screen': '<b>Рефералы</b>\n\nВаша ссылка:\n<code>{link}</code>\n\nПриглашено: <b>{count}</b>\nЗаработано: <b>{earned}</b> {internal_name}\nТекущая реферальная ставка: <b>{rate}%</b>\n\n{items}',
    'referrals_empty': 'Пока нет приглашённых пользователей. Поделитесь ссылкой, чтобы начать зарабатывать.',
    'referral_row': '• {name} — заработано: <b>{earned}</b> {internal_name} · вступил: <b>{joined}</b>',
}

TEXTS['en'].update(_STAGE6_TEXTS_EN)
TEXTS['ru'].update(_STAGE6_TEXTS_RU)
for _lang, _mapping in TEXTS.items():
    if _lang not in {'ru', 'en'}:
        for _key, _value in _STAGE6_TEXTS_EN.items():
            _mapping.setdefault(_key, _value)

_STAGE7_TEXTS_EN = {
    'menu_admin': 'Admin',
    'blocked_screen': '<b>Access restricted</b>\n\nYour account is temporarily blocked. If you think this is a mistake, contact support: {support}',
    'blocked_alert': 'Your account is blocked.',
    'proof_prompt': '<b>Task proof</b>\n\nSend one message with a link, @username, post ID or a short description. Standard tasks are credited to hold automatically, suspicious ones go to manual review.',
    'proof_sent_manual_review': 'Proof received. The task was sent to manual review.',
    'task_detail_manual_review': 'on manual review',
    'task_detail_rejected': 'rejected',
    'admin_access_denied': 'Admin access denied.',
    'admin_home_screen': '<b>Admin panel</b>\n\nManual review queue: <b>{queue}</b>\nBlocked users: <b>{blocked}</b>\nHigh-risk users: <b>{high_risk}</b>\nRejected submissions: <b>{rejected}</b>',
    'admin_queue_button': 'Review queue',
    'admin_logs_button': 'Admin logs',
    'admin_required_chats_button': 'Required subscriptions',
    'admin_required_chats_empty': '<b>Required subscriptions</b>\n\nThere are no required chats now. You can add up to <b>10</b>.',
    'admin_required_chats_screen': '<b>Required subscriptions</b>\n\nConfigured: <b>{count}/{limit}</b>\n\n{items}',
    'admin_required_chat_row': '• #{chat_id} · {name}\n  {link}',
    'admin_required_chat_add_button': 'Add chat',
    'admin_required_chat_remove_button': 'Remove: {name}',
    'admin_required_chat_add_prompt': '<b>Add required chat</b>\n\nSend one line in one of these formats:\n<code>@publicchannel</code>\n<code>https://t.me/publicchannel</code>\n<code>-1001234567890 https://t.me/+invite</code>\n\nFor private groups send numeric chat ID first and invite link second.',
    'admin_required_chat_added': 'Required chat added.',
    'admin_required_chat_removed': 'Required chat removed.',
    'admin_required_chat_exists': 'This chat is already in the required list.',
    'admin_required_chat_limit_reached': 'The required list already has 10 chats.',
    'admin_required_chat_invalid': 'Invalid format. Send @username, t.me link, or chat_id plus invite link.',
    'admin_required_chat_not_found': 'Required chat not found.',
    'admin_queue_empty': '<b>Manual review queue</b>\n\nQueue is empty right now.',
    'admin_queue_screen': '<b>Manual review queue</b>\n\n{items}',
    'admin_queue_line': '• #{submission_id} · {title} · {performer} · sub risk {risk} / user risk {user_risk}',
    'admin_queue_row': '#{submission_id} · {title} · {performer} · R{risk}',
    'admin_submission_not_found': 'Submission not found.',
    'admin_submission_already_reviewed': 'This submission has already been reviewed.',
    'admin_submission_screen': '<b>Submission #{submission_id}</b>\n\nCampaign: <b>{title}</b>\nPerformer: <b>{performer}</b>\nPerformer ID: <code>{performer_id}</code>\nUser status: <b>{user_status}</b>\nSubmission status: <b>{submission_status}</b>\nReward: <b>{reward}</b> XTR\nSubmission risk: <b>{submission_risk}</b>\nUser risk: <b>{user_risk}</b>\nApproved / rejected / review: <b>{approved}</b> / <b>{rejected}</b> / <b>{review_count}</b>\nSubmitted at: <b>{submitted_at}</b>\nTarget: <code>{target}</code>\nReject reason: <b>{reject_reason}</b>\n\n<b>Proof</b>\n<blockquote>{proof}</blockquote>\n\n<b>Recent risk events</b>\n{events}',
    'admin_risk_event_row': '• {created} · {event_type} · +{score}',
    'admin_risk_events_empty': 'No recent risk events.',
    'admin_approve_button': 'Approve',
    'admin_reject_button': 'Reject',
    'admin_block_button': 'Block user',
    'admin_unblock_button': 'Unblock user',
    'admin_adjust_risk_button': 'Adjust risk',
    'admin_adjust_balance_button': 'Adjust balance',
    'admin_submission_approved': 'Submission approved. Reward placed into hold.',
    'admin_submission_rejected': 'Submission rejected.',
    'admin_reject_prompt': '<b>Reject submission #{submission_id}</b>\n\nSend one text message with the rejection reason. It will be stored in moderation history.',
    'admin_reject_reason_empty': 'Reject reason cannot be empty.',
    'admin_user_not_found': 'User not found.',
    'admin_cannot_block_admin': 'You cannot block another admin.',
    'admin_user_blocked': 'User blocked.',
    'admin_user_unblocked': 'User unblocked.',
    'admin_adjust_risk_prompt': '<b>Adjust risk score</b>\n\nTarget: <b>{target}</b> · <code>{target_user_id}</code>\nCurrent risk: <b>{current}</b>\n\nSend a signed integer, for example <code>+10</code> or <code>-15</code>.',
    'admin_adjust_balance_prompt': '<b>Adjust available balance</b>\n\nTarget: <b>{target}</b> · <code>{target_user_id}</code>\n\nSend a signed integer in Sparks✨, for example <code>+100</code> or <code>-50</code>.',
    'admin_numeric_delta_invalid': 'Send a signed integer like +10 or -5.',
    'admin_risk_adjusted': 'Risk score updated.',
    'admin_balance_adjusted': 'Balance updated.',
    'admin_balance_adjust_invalid': 'Balance adjustment would make the balance negative.',
    'admin_logs_screen': '<b>Admin logs</b>\n\n{items}',
    'admin_logs_empty': '<b>Admin logs</b>\n\nNo admin actions yet.',
    'admin_log_row': '• {created} · admin {admin_id} · target {target_id} · {action} · {details}',
}

_STAGE7_TEXTS_RU = {
    'menu_admin': 'Админка',
    'blocked_screen': '<b>Доступ ограничен</b>\n\nВаш аккаунт временно заблокирован. Если это ошибка, напишите в поддержку: {support}',
    'blocked_alert': 'Ваш аккаунт заблокирован.',
    'proof_prompt': '<b>Подтверждение выполнения</b>\n\nОтправьте одним сообщением ссылку, @username, ID поста или краткое описание. Обычные задания автоматически уходят в холд, подозрительные — на ручную проверку.',
    'proof_sent_manual_review': 'Подтверждение получено. Задание отправлено на ручную проверку.',
    'task_detail_manual_review': 'на ручной проверке',
    'task_detail_rejected': 'отклонено',
    'admin_access_denied': 'Доступ к админке запрещён.',
    'admin_home_screen': '<b>Админка</b>\n\nВ очереди ручной проверки: <b>{queue}</b>\nЗаблокированных пользователей: <b>{blocked}</b>\nПользователей с высоким риском: <b>{high_risk}</b>\nВсего отклонённых выполнений: <b>{rejected}</b>',
    'admin_queue_button': 'Очередь проверок',
    'admin_logs_button': 'Логи админа',
    'admin_required_chats_button': 'Обязательные подписки',
    'admin_required_chats_empty': '<b>Обязательные подписки</b>\n\nСейчас обязательных чатов нет. Можно добавить до <b>10</b>.',
    'admin_required_chats_screen': '<b>Обязательные подписки</b>\n\nНастроено: <b>{count}/{limit}</b>\n\n{items}',
    'admin_required_chat_row': '• #{chat_id} · {name}\n  {link}',
    'admin_required_chat_add_button': 'Добавить чат',
    'admin_required_chat_remove_button': 'Удалить: {name}',
    'admin_required_chat_add_prompt': '<b>Добавление обязательного чата</b>\n\nОтправьте одной строкой один из вариантов:\n<code>@publicchannel</code>\n<code>https://t.me/publicchannel</code>\n<code>-1001234567890 https://t.me/+invite</code>\n\nДля приватной группы сначала укажите числовой chat ID, а вторым значением инвайт-ссылку.',
    'admin_required_chat_added': 'Обязательный чат добавлен.',
    'admin_required_chat_removed': 'Обязательный чат удалён.',
    'admin_required_chat_exists': 'Этот чат уже есть в списке обязательных.',
    'admin_required_chat_limit_reached': 'В списке обязательных уже 10 чатов.',
    'admin_required_chat_invalid': 'Неверный формат. Отправьте @username, ссылку t.me или chat_id вместе с invite link.',
    'admin_required_chat_not_found': 'Обязательный чат не найден.',
    'admin_queue_empty': '<b>Очередь ручной проверки</b>\n\nСейчас очередь пуста.',
    'admin_queue_screen': '<b>Очередь ручной проверки</b>\n\n{items}',
    'admin_queue_line': '• #{submission_id} · {title} · {performer} · риск выполнения {risk} / риск пользователя {user_risk}',
    'admin_queue_row': '#{submission_id} · {title} · {performer} · Р{risk}',
    'admin_submission_not_found': 'Выполнение не найдено.',
    'admin_submission_already_reviewed': 'Это выполнение уже было обработано.',
    'admin_submission_screen': '<b>Выполнение #{submission_id}</b>\n\nКампания: <b>{title}</b>\nИсполнитель: <b>{performer}</b>\nID исполнителя: <code>{performer_id}</code>\nСтатус пользователя: <b>{user_status}</b>\nСтатус выполнения: <b>{submission_status}</b>\nНаграда: <b>{reward}</b> XTR\nРиск выполнения: <b>{submission_risk}</b>\nОбщий риск пользователя: <b>{user_risk}</b>\nОдобрено / отклонено / на ручной: <b>{approved}</b> / <b>{rejected}</b> / <b>{review_count}</b>\nОтправлено: <b>{submitted_at}</b>\nЦель: <code>{target}</code>\nПричина отклонения: <b>{reject_reason}</b>\n\n<b>Подтверждение</b>\n<blockquote>{proof}</blockquote>\n\n<b>Последние риск-события</b>\n{events}',
    'admin_risk_event_row': '• {created} · {event_type} · +{score}',
    'admin_risk_events_empty': 'Недавних риск-событий нет.',
    'admin_approve_button': 'Одобрить',
    'admin_reject_button': 'Отклонить',
    'admin_block_button': 'Заблокировать',
    'admin_unblock_button': 'Разблокировать',
    'admin_adjust_risk_button': 'Скорректировать риск',
    'admin_adjust_balance_button': 'Скорректировать баланс',
    'admin_submission_approved': 'Выполнение одобрено. Награда отправлена в холд.',
    'admin_submission_rejected': 'Выполнение отклонено.',
    'admin_reject_prompt': '<b>Отклонение выполнения #{submission_id}</b>\n\nОтправьте одним сообщением причину отклонения. Она сохранится в истории модерации.',
    'admin_reject_reason_empty': 'Причина отклонения не может быть пустой.',
    'admin_user_not_found': 'Пользователь не найден.',
    'admin_cannot_block_admin': 'Нельзя заблокировать другого администратора.',
    'admin_user_blocked': 'Пользователь заблокирован.',
    'admin_user_unblocked': 'Пользователь разблокирован.',
    'admin_adjust_risk_prompt': '<b>Корректировка risk score</b>\n\nЦель: <b>{target}</b> · <code>{target_user_id}</code>\nТекущий риск: <b>{current}</b>\n\nОтправьте целое число со знаком, например <code>+10</code> или <code>-15</code>.',
    'admin_adjust_balance_prompt': '<b>Корректировка доступного баланса</b>\n\nЦель: <b>{target}</b> · <code>{target_user_id}</code>\n\nОтправьте целое число со знаком в Искрах✨, например <code>+100</code> или <code>-50</code>.',
    'admin_numeric_delta_invalid': 'Отправьте целое число со знаком, например +10 или -5.',
    'admin_risk_adjusted': 'Risk score обновлён.',
    'admin_balance_adjusted': 'Баланс обновлён.',
    'admin_balance_adjust_invalid': 'После корректировки баланс стал бы отрицательным.',
    'admin_logs_screen': '<b>Логи админа</b>\n\n{items}',
    'admin_logs_empty': '<b>Логи админа</b>\n\nАдмин-действий пока нет.',
    'admin_log_row': '• {created} · админ {admin_id} · цель {target_id} · {action} · {details}',
}

TEXTS['en'].update(_STAGE7_TEXTS_EN)
TEXTS['ru'].update(_STAGE7_TEXTS_RU)
for _lang, _mapping in TEXTS.items():
    if _lang not in {'ru', 'en'}:
        for _key, _value in _STAGE7_TEXTS_EN.items():
            _mapping.setdefault(_key, _value)


TEXTS['ru'].update({
    'menu_campaigns': 'Создать задание',
    'wallet_screen': """<b>Кошелёк</b>

Искры для обмена: <b>{internal}</b> {internal_name}
Бонус на запуск заданий: <b>{bonus}</b> {internal_name}
Всего на запуск заданий: <b>{campaign_balance}</b> {internal_name}
В холде: <b>{hold}</b> {internal_name}
Всего заработано: <b>{earned}</b> {internal_name}
Доступ к обмену: <b>{redeem_access}</b>
Освобождено холдов сейчас: <b>{released}</b>""",
    'campaign_create_intro': """<b>Создать задание</b>

Выберите тип задания. Дальше бот попросит ссылку, количество и цену за 1 выполнение.

Вы можете поставить цену сами, но не ниже базовой. Чем выше цена, тем выше награда исполнителю и тем быстрее обычно идёт выполнение.

Стартовый бонус начисляется только на запуск заданий и не участвует в обмене/выводе.""",
    'campaign_target_prompt': 'Отправьте ссылку, @username или t.me-ссылку цели задания.',
    'campaign_quantity_prompt': 'Отправьте нужное количество выполнений целым числом. Базовая цена снижается от объёма автоматически.',
    'campaign_price_prompt': 'Теперь отправьте цену за 1 выполнение в {currency}. Минимум: <b>{floor}</b>. Можно отправить <code>0</code> или <code>авто</code>, чтобы взять базовую цену.',
    'campaign_input_screen': """<b>Создать задание</b>

Шаг: <b>{step}</b>
Тип: <b>{task_type}</b>
Цель: <b>{target_url}</b>
Количество: <b>{quantity}</b>
База за 1: <b>{floor}</b> {internal_name}
Текущая цена за 1: <b>{unit_price}</b> {internal_name}
Награда исполнителю: <b>{reward}</b> {internal_name}""",
    'campaign_preview_screen': """<b>Предпросмотр задания</b>

Тип: <b>{task_type}</b>
Цель: <b>{target_url}</b>
Количество: <b>{quantity}</b>
Базовая цена за 1: <b>{floor}</b> {internal_name}
Ваша цена за 1: <b>{unit_price}</b> {internal_name}
Базовая награда исполнителю: <b>{reward_floor}</b> {internal_name}
Итоговая награда исполнителю: <b>{reward}</b> {internal_name}
Скидка за объём: <b>{discount}%</b>
Ориентир скорости: <b>{speed}%</b> от базовой
Комиссия сервиса: <b>{fee}</b> {internal_name}
Итого к списанию: <b>{budget}</b> {internal_name}""",
    'campaigns_empty': """<b>Мои задания</b>

У вас пока нет созданных заданий. Нажмите «Создать задание».""",
    'campaigns_screen': """<b>Мои задания</b>

Всего: <b>{total}</b>
Активных: <b>{active}</b>
На паузе: <b>{paused}</b>
Черновиков: <b>{drafts}</b>""",
    'campaign_create_button': 'Создать задание',
    'back_to_campaigns': 'К моим заданиям',
    'campaign_price_invalid': 'Введите целое число, 0 или слово «авто».',
    'campaign_price_below_floor': 'Цена ниже базовой. Поставьте не меньше базовой цены.',
    'campaign_price_saved': 'Цена сохранена. Проверьте предпросмотр.',
    'rewards_screen': """<b>Обмен и пополнение</b>

Искры для обмена: <b>{balance}</b> {internal_name}
Бонусные Искры: <b>{bonus}</b> {internal_name}
Доступ к обмену: <b>{redeem_access}</b>

<b>Бусты</b>
{items}

<b>Telegram Premium</b>
{premium_items}

<b>Подарки Telegram</b>
{gift_items}

<b>Заявки на вывод</b>
{cashout_items}

Ниже доступны пакеты пополнения за Telegram Stars.""",
    'redeem_access_yes': 'есть',
    'redeem_access_no': 'нужен хотя бы 1 успешный платёж Stars',
    'redeem_access_denied': 'Обмен доступен только после хотя бы одного успешного пополнения за Stars.',
    'redeem_balance_low': 'Недостаточно Искр для этого обмена.',
    'redeem_offer_not_found': 'Предложение больше недоступно. Обновите экран.',
    'redeem_catalog_unavailable': 'Каталог Telegram сейчас недоступен.',
    'redeem_telegram_failed': 'Telegram не подтвердил операцию. Искры возвращены обратно.',
    'premium_redeem_success': 'Telegram Premium отправлен на ваш аккаунт.',
    'gift_redeem_success': 'Подарок отправлен на ваш аккаунт.',
    'cashout_request_created': 'Заявка на вывод создана и отправлена владельцу на ручную обработку.',
    'reward_item_row': '• {title} · {price} {internal_name}',
    'campaign_task_type_post_comment': 'Комментарий под постом',
    'campaign_task_type_poll_vote': 'Голос в опросе',
})

TEXTS['en'].update({
    'menu_campaigns': 'Create task',
    'wallet_screen': """<b>Wallet</b>

Redeemable Sparks: <b>{internal}</b> {internal_name}
Bonus for launching tasks: <b>{bonus}</b> {internal_name}
Total for task launch: <b>{campaign_balance}</b> {internal_name}
In hold: <b>{hold}</b> {internal_name}
Lifetime earned: <b>{earned}</b> {internal_name}
Redeem access: <b>{redeem_access}</b>
Released now: <b>{released}</b>""",
    'campaign_price_invalid': 'Send an integer, 0 or auto.',
    'campaign_price_below_floor': 'The price is below the base floor price.',
    'campaign_price_saved': 'Price saved. Check the preview.',
    'campaign_task_type_post_comment': 'Comment under post',
    'campaign_task_type_poll_vote': 'Vote in poll',
    'redeem_access_yes': 'available',
    'redeem_access_no': 'need at least one successful Stars top-up',
    'redeem_access_denied': 'Redeem is available only after at least one successful Stars top-up.',
    'redeem_balance_low': 'Not enough Sparks for this redeem.',
    'redeem_offer_not_found': 'Offer is no longer available. Refresh the screen.',
    'redeem_catalog_unavailable': 'Telegram catalog is unavailable right now.',
    'redeem_telegram_failed': 'Telegram did not confirm the operation. Sparks were refunded.',
    'premium_redeem_success': 'Telegram Premium has been sent to your account.',
    'gift_redeem_success': 'Gift has been sent to your account.',
    'cashout_request_created': 'Cashout request created and sent to the owner for manual processing.',
})

for _lang, _mapping in TEXTS.items():
    if _lang not in {'ru', 'en'}:
        _mapping.setdefault('menu_campaigns', 'Create task')
        _mapping.setdefault('campaign_price_invalid', 'Send an integer, 0 or auto.')
        _mapping.setdefault('campaign_price_below_floor', 'The price is below the base floor price.')
        _mapping.setdefault('campaign_price_saved', 'Price saved. Check the preview.')
        _mapping.setdefault('redeem_access_yes', 'available')
        _mapping.setdefault('redeem_access_no', 'need at least one successful Stars top-up')
        _mapping.setdefault('redeem_access_denied', 'Redeem is available only after at least one successful Stars top-up.')
        _mapping.setdefault('redeem_balance_low', 'Not enough Sparks for this redeem.')
        _mapping.setdefault('redeem_offer_not_found', 'Offer is no longer available. Refresh the screen.')
        _mapping.setdefault('redeem_catalog_unavailable', 'Telegram catalog is unavailable right now.')
        _mapping.setdefault('redeem_telegram_failed', 'Telegram did not confirm the operation. Sparks were refunded.')
        _mapping.setdefault('premium_redeem_success', 'Telegram Premium has been sent to your account.')
        _mapping.setdefault('gift_redeem_success', 'Gift has been sent to your account.')
        _mapping.setdefault('cashout_request_created', 'Cashout request created and sent to the owner for manual processing.')
        _mapping.setdefault('campaign_task_type_post_comment', 'Comment under post')
        _mapping.setdefault('campaign_task_type_poll_vote', 'Vote in poll')

# Final runtime text overrides for the working production build.
TEXTS['ru'].update({
    'internal_currency_name': 'Искры✨',
    'menu_campaigns': 'Создать задание',
    'campaigns_screen': '<b>Ваши задания</b>\n\nВсего: <b>{total}</b>\nАктивных: <b>{active}</b>\nНа паузе: <b>{paused}</b>\nЧерновиков: <b>{drafts}</b>',
    'campaigns_empty': '<b>Ваши задания</b>\n\nПока заданий нет. Нажмите кнопку ниже, чтобы создать первое.',
    'campaign_create_button': 'Создать задание',
    'back_to_campaigns': 'К заданиям',
    'profile_screen': '<b>Профиль</b>\n\nID: <code>{profile_id}</code>\nРоль: <b>{role}</b>\nАктивных заданий: <b>{active_tasks}/{task_limit}</b>\nИскры для обмена: <b>{sparks}</b> {internal_name}\nБонус на запуск заданий: <b>{bonus}</b> {internal_name}\nВсего на запуск заданий: <b>{campaign_balance}</b> {internal_name}\nВ холде: <b>{hold}</b> {internal_name}\nВсего заработано: <b>{earned}</b> {internal_name}\nДоступ к обмену: <b>{redeem_access}</b>',
    'wallet_screen': '<b>Кошелёк👛</b>\n\nИскры для обмена: <b>{internal}</b> {internal_name}\nБонус на запуск заданий: <b>{bonus}</b> {internal_name}\nВсего на запуск заданий: <b>{campaign_balance}</b> {internal_name}\nВ холде: <b>{hold}</b> {internal_name}\nВсего заработано: <b>{earned}</b> {internal_name}\nДоступ к обмену: <b>{redeem_access}</b>\nОсвобождено холдов сейчас: <b>{released}</b>',
    'wallet_topup_button': 'Пополнить за ⭐',
    'task_row': '• {title} · {reward} {internal_name}',
    'task_detail': '<b>{title}</b>\n\nТип: <b>{task_type}</b>\nНаграда: <b>{reward}</b> {internal_name}\nДоступно: <b>{remaining}</b>\n\nСтатус: <b>{status}</b>\n\nОткройте цель задания, затем возьмите его или отправьте подтверждение.',
    'task_detail_manual_review': 'на ручной проверке',
    'task_detail_rejected': 'отклонено',
    'history_screen': '<b>История операций</b>\n\n{items}',
    'history_row': '• {date} · {entry_type} · {amount} {currency} · {status}',
    'vip_screen': '<b>VIP</b>\n\n{active_block}\n\nСуммарные бонусы сейчас:\n• Ускорение холда: <b>{hold_speed}%</b>\n• Доп. лимит активных заданий: <b>+{task_bonus}</b>\n• Приоритет очереди: <b>{priority}</b>\n• Бонус к реферальной ставке: <b>+{ref_bonus}%</b>\n\n<b>Что даёт VIP</b>\n{plans_block}\n\nМожно купить за {internal_name} или за Telegram Stars: 7 дней — <b>{stars_7}⭐</b>, 30 дней — <b>{stars_30}⭐</b>.',
    'vip_plan_row': '• <b>{title}</b> — {price} {internal_name}\n  {desc}',
    'rewards_screen': '<b>Искры✨ и обмен</b>\n\nИскры для обмена: <b>{balance}</b> {internal_name}\nБонусные Искры: <b>{bonus}</b> {internal_name}\nДоступ к обмену: <b>{redeem_access}</b>\n\n<b>Бонусы</b>\n{items}\n\n<b>Telegram Premium</b>\n{premium_items}\n\n<b>Подарки Telegram</b>\n{gift_items}\n\n<b>Вывод</b>\n{cashout_items}\n\nНиже доступны пакеты пополнения за Telegram Stars.',
    'redeem_cashout_manual': 'Автоматический вывод звёзд ботом не показывается. Для обмена доступны Telegram Premium и Telegram Gifts. Общий вывод можно добавить позже как ручную заявку владельцу.',
    'campaign_input_screen': '<b>Создать задание</b>\n\nШаг: <b>{step}</b>\nТип: <b>{task_type}</b>\nЦель: <b>{target_url}</b>\nКоличество: <b>{quantity}</b>\nБаза за 1: <b>{floor}</b> {internal_name}\nТекущая цена за 1: <b>{unit_price}</b> {internal_name}\nНаграда исполнителю: <b>{reward}</b> {internal_name}',
    'campaign_target_prompt': 'Отправьте ссылку, @username или tg:// ссылку цели.',
    'campaign_quantity_prompt': 'Отправьте количество выполнений целым числом.',
    'campaign_price_prompt': 'Отправьте цену за 1 выполнение. Минимум: <b>{floor}</b> {currency}. Можно поставить выше, чтобы задание выполнили быстрее.',
    'campaign_preview_screen': '<b>Предпросмотр задания</b>\n\nТип: <b>{task_type}</b>\nЦель: <b>{target_url}</b>\nКоличество: <b>{quantity}</b>\nБазовая цена за 1: <b>{floor}</b> {internal_name}\nВаша цена за 1: <b>{unit_price}</b> {internal_name}\nБазовая награда исполнителю: <b>{reward_floor}</b> {internal_name}\nИтоговая награда исполнителю: <b>{reward}</b> {internal_name}\nСкидка за объём: <b>{discount}%</b>\nОриентир скорости: <b>{speed}%</b> от базы\nКомиссия сервиса: <b>{fee}</b> {internal_name}\nИтого к списанию: <b>{budget}</b> {internal_name}',
    'campaign_card_screen': '<b>Задание #{campaign_id}</b>\n\nНазвание: <b>{title}</b>\nТип: <b>{task_type}</b>\nЦель: <b>{target_url}</b>\nНаграда исполнителю: <b>{reward}</b> {internal_name}\nЦена заказчика за 1: <b>{unit_price}</b> {internal_name}\nКоличество: <b>{quantity}</b>\nВыполнено: <b>{completed}</b>\nОтклонено: <b>{rejected}</b>\nБюджет: <b>{budget_total}</b> {internal_name}\nПотрачено: <b>{budget_spent}</b> {internal_name}\nВ резерве: <b>{budget_reserved}</b> {internal_name}\nОстаток: <b>{budget_remaining}</b> {internal_name}\nКомиссия сервиса: <b>{fee_total}</b> {internal_name}\nБаланс списан: <b>{funded}</b>\nСтатус: <b>{status}</b>',
    'campaign_stats_screen': '<b>Аналитика</b>\n\nВсего заданий: <b>{total}</b>\nАктивных: <b>{active}</b>\nНа паузе: <b>{paused}</b>\nЧерновиков: <b>{drafts}</b>\nВыполнено: <b>{completed}</b>\nОтклонено: <b>{rejected}</b>\nОбщий бюджет: <b>{budget}</b> {internal_name}\nПотрачено: <b>{spent}</b> {internal_name}\nВ резерве: <b>{reserved}</b> {internal_name}\nОстаток: <b>{remaining}</b> {internal_name}\nКомиссия сервиса: <b>{fees}</b> {internal_name}\nФонд выплат исполнителям: <b>{rewards}</b> {internal_name}',
    'campaign_balance_low': 'Недостаточно Искр✨ для запуска задания.',
    'campaign_created_active': 'Задание создано и запущено.',
    'campaign_created_draft': 'Задание сохранено в черновики.',
    'campaign_launched': 'Задание запущено.',
    'campaign_paused': 'Задание поставлено на паузу.',
    'campaign_resumed': 'Задание снова активно.',
    'campaign_status_draft': 'черновик',
    'campaign_status_active': 'активно',
    'campaign_status_paused': 'на паузе',
    'campaign_status_completed': 'завершено',
    'campaign_status_archived': 'в архиве',
    'reward_item_row': '• {title} · {price} {internal_name}',
    'vip_purchase_success': 'VIP успешно активирован.',
    'vip_balance_low': 'Недостаточно Искр✨ для покупки VIP.',
    'reward_purchase_success': 'Бонус успешно активирован.',
    'reward_balance_low': 'Недостаточно Искр✨ для покупки бонуса.',
    'payment_pack_not_found': 'Пакет пополнения не найден.',
    'stars_topup_success': 'Пополнение зачислено: <b>{amount}</b> {internal_name}.',
    'vip_stars_success': 'VIP активирован после оплаты Stars.',
    'redeem_access_yes': 'открыт',
    'redeem_access_no': 'нужно хотя бы одно успешное пополнение за ⭐',
    'redeem_access_denied': 'Обмен доступен только после хотя бы одного успешного пополнения за ⭐.',
    'redeem_balance_low': 'Недостаточно Искр✨ для обмена.',
    'redeem_offer_not_found': 'Предложение больше недоступно. Обновите экран.',
    'redeem_catalog_unavailable': 'Каталог Telegram сейчас недоступен.',
    'redeem_telegram_failed': 'Telegram не подтвердил операцию. Искры вернулись на баланс.',
    'premium_redeem_success': 'Telegram Premium успешно отправлен на ваш аккаунт.',
    'gift_redeem_success': 'Подарок Telegram успешно отправлен на ваш аккаунт.',
    'cashout_request_created': 'Заявка создана и отправлена владельцу для ручной обработки.',
    'tx_signup_bonus': 'Стартовый бонус',
    'tx_task_reward_hold': 'Награда за задание в холде',
    'tx_hold_release': 'Освобождение холда',
    'tx_campaign_funding': 'Запуск задания',
    'tx_campaign_funding_bonus': 'Запуск задания из бонуса',
    'tx_stars_topup': 'Пополнение за Stars',
    'tx_vip_purchase': 'Покупка VIP',
    'tx_reward_purchase': 'Покупка бонуса',
    'tx_referral_reward': 'Реферальная награда',
    'tx_gift_redeem': 'Обмен на подарок Telegram',
    'tx_gift_refund': 'Возврат за подарок',
    'tx_premium_redeem': 'Обмен на Telegram Premium',
    'tx_premium_refund': 'Возврат за Premium',
    'status_completed': 'завершено',
    'status_hold': 'в холде',
    'status_pending': 'ожидает',
    'status_active': 'активно',
    'status_rejected': 'отклонено',
})

TEXTS['en'].update({
    'internal_currency_name': 'Sparks✨',
    'menu_campaigns': 'Create task',
    'wallet_topup_button': 'Top up with ⭐',
    'payment_pack_not_found': 'Top-up pack not found.',
    'stars_topup_success': 'Top-up credited: <b>{amount}</b> {internal_name}.',
    'vip_stars_success': 'VIP activated after the Stars payment.',
    'tx_signup_bonus': 'Signup bonus',
    'tx_task_reward_hold': 'Task reward on hold',
    'tx_hold_release': 'Hold release',
    'tx_campaign_funding': 'Task launch',
    'tx_campaign_funding_bonus': 'Task launch from bonus',
    'tx_stars_topup': 'Stars top-up',
    'tx_vip_purchase': 'VIP purchase',
    'tx_reward_purchase': 'Boost purchase',
    'tx_referral_reward': 'Referral reward',
    'tx_gift_redeem': 'Telegram Gift redeem',
    'tx_gift_refund': 'Gift refund',
    'tx_premium_redeem': 'Telegram Premium redeem',
    'tx_premium_refund': 'Premium refund',
    'status_completed': 'completed',
    'status_hold': 'on hold',
    'status_pending': 'pending',
    'status_active': 'active',
    'status_rejected': 'rejected',
})

for _lang, _mapping in TEXTS.items():
    if _lang not in {'ru', 'en'}:
        _mapping.setdefault('internal_currency_name', 'Sparks✨')
        _mapping.setdefault('menu_campaigns', 'Create task')
        _mapping.setdefault('wallet_topup_button', 'Top up with ⭐')
        _mapping.setdefault('payment_pack_not_found', 'Top-up pack not found.')
        _mapping.setdefault('stars_topup_success', 'Top-up credited: <b>{amount}</b> {internal_name}.')
        _mapping.setdefault('vip_stars_success', 'VIP activated after the Stars payment.')
        _mapping.setdefault('status_completed', 'completed')
        _mapping.setdefault('status_hold', 'on hold')
        _mapping.setdefault('status_pending', 'pending')
        _mapping.setdefault('status_active', 'active')
        _mapping.setdefault('status_rejected', 'rejected')


# Final support overrides after bugfixes.
TEXTS['ru'].update({
    'internal_currency_name': 'Искры✨',
    'menu_profile': 'Профиль',
    'menu_wallet': 'Кошелёк👛',
    'menu_campaigns': 'Создать задание',
    'profile_screen': '<b>Профиль</b>\n\nID: <code>{profile_id}</code>\nРоль: <b>{role}</b>\nАктивных заданий: <b>{active_tasks}/{task_limit}</b>\nИскры для обмена: <b>{internal}</b> {internal_name}\nБонусные Искры для запуска: <b>{bonus}</b> {internal_name}\nВсего на запуск заданий: <b>{campaign_balance}</b> {internal_name}\nВ холде: <b>{hold}</b> {internal_name}\nВсего заработано: <b>{earned}</b> {internal_name}\nДоступ к обмену: <b>{redeem_access}</b>',
    'wallet_screen': '<b>Кошелёк👛</b>\n\nИскры для обмена: <b>{internal}</b> {internal_name}\nБонусные Искры для запуска: <b>{bonus}</b> {internal_name}\nВсего на запуск заданий: <b>{campaign_balance}</b> {internal_name}\nВ холде: <b>{hold}</b> {internal_name}\nВсего заработано: <b>{earned}</b> {internal_name}\nДоступ к обмену: <b>{redeem_access}</b>\nОсвобождено холдов сейчас: <b>{released}</b>',
    'history_screen': '<b>История операций</b>\n\n{items}',
    'history_row': '• {date} · {entry_type} · {amount} {currency} · {status}',
    'tx_signup_bonus': 'Стартовый бонус',
    'tx_task_reward_hold': 'Награда за задание в холде',
    'tx_hold_release': 'Освобождение холда',
    'tx_campaign_funding': 'Запуск задания',
    'tx_campaign_funding_bonus': 'Запуск задания из бонусных Искр',
    'tx_stars_topup': 'Пополнение за Stars',
    'tx_vip_purchase': 'Покупка VIP',
    'tx_reward_purchase': 'Покупка бонуса',
    'tx_referral_reward': 'Реферальная награда',
    'tx_gift_redeem': 'Обмен на подарок Telegram',
    'tx_gift_refund': 'Возврат за подарок Telegram',
    'tx_premium_redeem': 'Обмен на Telegram Premium',
    'tx_premium_refund': 'Возврат за Premium',
    'status_completed': 'завершено',
    'status_hold': 'в холде',
    'status_pending': 'ожидает',
    'status_active': 'активно',
    'status_rejected': 'отклонено',
    'wallet_topup_button': 'Пополнить Искры за ⭐',
    'vip_screen': '<b>VIP</b>\n\n{active_block}\n\n<b>Что даёт VIP</b>\n• ускоряет выход из холда\n• увеличивает лимит активных заданий\n• даёт приоритет в очереди\n• усиливает реферальную ставку\n\n<b>Ваши текущие бонусы</b>\n• Ускорение холда: <b>{hold_speed}%</b>\n• Доп. лимит активных заданий: <b>+{task_bonus}</b>\n• Приоритет очереди: <b>{priority}</b>\n• Бонус к реферальной ставке: <b>+{ref_bonus}%</b>\n\n<b>Тарифы</b>\n{plans_block}\n\nМожно купить за {internal_name} или за Telegram Stars: 7 дней — <b>{stars_7}⭐</b>, 30 дней — <b>{stars_30}⭐</b>.',
    'vip_plan_row': '• <b>{title}</b> — {price} {internal_name}\n  {desc}',
    'vip_plan_7_desc': 'Холд быстрее на 25%, +2 активных задания, приоритет 1, +2% к реферальной ставке.',
    'vip_plan_30_desc': 'Холд быстрее на 50%, +5 активных заданий, приоритет 2, +5% к реферальной ставке.',
    'rewards_screen': '<b>Искры✨, Premium и подарки</b>\n\nИскры для обмена: <b>{balance}</b> {internal_name}\nБонусные Искры для запуска: <b>{bonus}</b> {internal_name}\nДоступ к обмену: <b>{redeem_access}</b>\n\n<b>Бонусы</b>\n{items}\n\n<b>Telegram Premium</b>\n{premium_items}\n\n<b>Подарки Telegram</b>\n{gift_items}\n\nПополнение ниже — за Telegram Stars.',
    'redeem_cashout_manual': 'Общий автоматический вывод звёзд не показывается. Доступны реальные Telegram Premium и Telegram Gifts.',
    'redeem_catalog_unavailable': 'Каталог Telegram сейчас недоступен.',
    'gift_redeem_success': 'Подарок Telegram отправлен на ваш аккаунт.',
    'premium_redeem_success': 'Telegram Premium отправлен на ваш аккаунт.',
    'stars_topup_success': 'Пополнение зачислено: <b>{amount}</b> {internal_name}.',
    'vip_stars_success': 'VIP активирован после оплаты Stars.',
    'redeem_access_yes': 'открыт',
    'redeem_access_no': 'нужно хотя бы одно успешное пополнение за ⭐',
    'campaigns_screen': '<b>Ваши задания</b>\n\nВсего: <b>{total}</b>\nАктивных: <b>{active}</b>\nНа паузе: <b>{paused}</b>\nЧерновиков: <b>{drafts}</b>',
    'campaigns_empty': '<b>Ваши задания</b>\n\nПока заданий нет. Нажмите кнопку ниже, чтобы создать первое.',
    'campaign_create_button': 'Создать задание',
    'campaign_create_intro': '<b>Создать задание</b>\n\nВыберите тип задания для новой кампании.',
    'campaign_input_screen': '<b>Создать задание</b>\n\nШаг: <b>{step}</b>\nТип: <b>{task_type}</b>\nЦель: <b>{target_url}</b>\nКоличество: <b>{quantity}</b>\nБаза за 1: <b>{floor}</b> {internal_name}\nТекущая цена за 1: <b>{unit_price}</b> {internal_name}\nНаграда исполнителю: <b>{reward}</b> {internal_name}',
    'campaign_price_prompt': 'Отправьте цену за 1 выполнение. Минимум: <b>{floor}</b> {currency}. Можно поставить выше, чтобы ускорить выполнение.',
    'campaign_preview_screen': '<b>Предпросмотр задания</b>\n\nТип: <b>{task_type}</b>\nЦель: <b>{target_url}</b>\nКоличество: <b>{quantity}</b>\nБазовая цена за 1: <b>{floor}</b> {internal_name}\nВаша цена за 1: <b>{unit_price}</b> {internal_name}\nБазовая награда исполнителю: <b>{reward_floor}</b> {internal_name}\nИтоговая награда исполнителю: <b>{reward}</b> {internal_name}\nСкидка за объём: <b>{discount}%</b>\nОриентир скорости: <b>{speed}%</b> от базы\nКомиссия сервиса: <b>{fee}</b> {internal_name}\nИтого к списанию: <b>{budget}</b> {internal_name}',
    'campaign_card_screen': '<b>Задание #{campaign_id}</b>\n\nНазвание: <b>{title}</b>\nТип: <b>{task_type}</b>\nЦель: <b>{target_url}</b>\nНаграда исполнителю: <b>{reward}</b> {internal_name}\nЦена заказчика за 1: <b>{unit_price}</b> {internal_name}\nКоличество: <b>{quantity}</b>\nВыполнено: <b>{completed}</b>\nОтклонено: <b>{rejected}</b>\nБюджет: <b>{budget_total}</b> {internal_name}\nПотрачено: <b>{budget_spent}</b> {internal_name}\nВ резерве: <b>{budget_reserved}</b> {internal_name}\nОстаток: <b>{budget_remaining}</b> {internal_name}\nКомиссия сервиса: <b>{fee_total}</b> {internal_name}\nБаланс списан: <b>{funded}</b>\nСтатус: <b>{status}</b>',
    'campaign_stats_screen': '<b>Аналитика</b>\n\nВсего заданий: <b>{total}</b>\nАктивных: <b>{active}</b>\nНа паузе: <b>{paused}</b>\nЧерновиков: <b>{drafts}</b>\nВыполнено: <b>{completed}</b>\nОтклонено: <b>{rejected}</b>\nОбщий бюджет: <b>{budget}</b> {internal_name}\nПотрачено: <b>{spent}</b> {internal_name}\nВ резерве: <b>{reserved}</b> {internal_name}\nОстаток: <b>{remaining}</b> {internal_name}\nКомиссия сервиса: <b>{fees}</b> {internal_name}\nФонд выплат исполнителям: <b>{rewards}</b> {internal_name}',
    'campaign_balance_low': 'Недостаточно Искр✨ для запуска задания.',
})

TEXTS['en'].update({
    'internal_currency_name': 'Sparks✨',
    'menu_campaigns': 'Create task',
    'menu_wallet': 'Wallet👛',
    'profile_screen': '<b>Profile</b>\n\nID: <code>{profile_id}</code>\nRole: <b>{role}</b>\nActive tasks: <b>{active_tasks}/{task_limit}</b>\nRedeemable Sparks: <b>{internal}</b> {internal_name}\nBonus Sparks for launching tasks: <b>{bonus}</b> {internal_name}\nTotal launch balance: <b>{campaign_balance}</b> {internal_name}\nIn hold: <b>{hold}</b> {internal_name}\nLifetime earned: <b>{earned}</b> {internal_name}\nRedeem access: <b>{redeem_access}</b>',
    'wallet_screen': '<b>Wallet👛</b>\n\nRedeemable Sparks: <b>{internal}</b> {internal_name}\nBonus Sparks for launching tasks: <b>{bonus}</b> {internal_name}\nTotal launch balance: <b>{campaign_balance}</b> {internal_name}\nIn hold: <b>{hold}</b> {internal_name}\nLifetime earned: <b>{earned}</b> {internal_name}\nRedeem access: <b>{redeem_access}</b>\nReleased now: <b>{released}</b>',
    'wallet_topup_button': 'Top up Sparks with ⭐',
    'vip_screen': '<b>VIP</b>\n\n{active_block}\n\n<b>What VIP gives</b>\n• faster hold release\n• more active task slots\n• queue priority\n• stronger referral rate\n\n<b>Your current bonuses</b>\n• Hold speed: <b>{hold_speed}%</b>\n• Extra active task slots: <b>+{task_bonus}</b>\n• Queue priority: <b>{priority}</b>\n• Referral bonus: <b>+{ref_bonus}%</b>\n\n<b>Plans</b>\n{plans_block}\n\nYou can buy VIP with {internal_name} or Telegram Stars: 7 days — <b>{stars_7}⭐</b>, 30 days — <b>{stars_30}⭐</b>.',
    'rewards_screen': '<b>Sparks✨, Premium and gifts</b>\n\nRedeemable Sparks: <b>{balance}</b> {internal_name}\nBonus Sparks for launching tasks: <b>{bonus}</b> {internal_name}\nRedeem access: <b>{redeem_access}</b>\n\n<b>Boosts</b>\n{items}\n\n<b>Telegram Premium</b>\n{premium_items}\n\n<b>Telegram Gifts</b>\n{gift_items}\n\nThe packs below are paid with Telegram Stars.',
    'redeem_cashout_manual': 'General automatic star withdrawal is hidden. Real Telegram Premium and Telegram Gifts are available.',
})

for _lang, _mapping in TEXTS.items():
    if _lang not in {'ru', 'en'}:
        _mapping.setdefault('internal_currency_name', 'Sparks✨')
        _mapping.setdefault('wallet_topup_button', 'Top up Sparks with ⭐')
